#!/usr/bin/env python3
"""Generate supabase/migrations/*.sql from docs/design/schema.sql.

    python3 scripts/build_migrations.py           # write the migration files
    python3 scripts/build_migrations.py --check   # fail if the committed files have drifted

`docs/design/schema.sql` is the single source of truth for the schema: it is the file reviewers read
alongside the design document. Hand-copying slices of it into migrations would guarantee the two
diverge within a month, so the migrations are generated and drift is a build failure.

The split is by the numbered banner sections in schema.sql, chosen so each migration can be reviewed
as one idea:

    0001_core   conventions + identity, events, participation
    0002_money  money tables, the functions that do the work, views, audit triggers
    0003_rls    every row-level security policy in one file

Phase-2 sections (9 hosted tournaments, 10 push/notifications) are not emitted yet; they become
0005 and 0004 when their milestones land.
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "design" / "schema.sql"
OUT_DIR = ROOT / "supabase" / "migrations"

# migration file -> (title, [section numbers from schema.sql])
PLAN = {
    "0001_core.sql": ("identity, events and participation", [0, 1, 2, 3]),
    "0002_money.sql": ("money, the functions that do the work, views and audit", [4, 5, 6, 8]),
    "0003_rls.sql": ("row-level security policies and role helpers", [7]),
}

BANNER = re.compile(r"^-- (\d+)\. ")
RULE = "-- " + "=" * 69

HEADER = """-- =====================================================================
-- CalBlue — migration {name}
-- {title}
--
-- GENERATED from docs/design/schema.sql by scripts/build_migrations.py.
-- Do not edit this file directly: edit schema.sql and regenerate, or
-- scripts/check_sql.py --check will fail on the drift.
-- =====================================================================

"""


def parse_sections(text):
    """Split schema.sql into {section_number: source_text}."""
    lines = text.split("\n")
    starts = []
    for i, line in enumerate(lines):
        m = BANNER.match(line)
        if not m:
            continue
        # A real section banner is preceded by a ruler line. Section 0 uses a dashed ruler,
        # the rest use "-- ====", so both '-' and '=' are permitted.
        prev = lines[i - 1] if i else ""
        if set(prev.strip()) <= {"-", "=", " "} and len(prev.strip()) > 20:
            starts.append((int(m.group(1)), i - 1))

    sections = {}
    for idx, (number, start) in enumerate(starts):
        end = starts[idx + 1][1] if idx + 1 < len(starts) else len(lines)
        sections[number] = "\n".join(lines[start:end]).rstrip() + "\n"

    # Everything above the first section is the file header plus the CREATE EXTENSION
    # statements. Those are not optional — gen_random_uuid() and citext depend on them —
    # so they ride along with whichever migration carries section 0.
    preamble_lines = [l for l in lines[: starts[0][1]] if l.startswith("create extension")]
    sections["_preamble"] = "\n".join(preamble_lines).rstrip() + "\n"
    return sections


def build():
    sections = parse_sections(SOURCE.read_text())
    missing = {n for _, nums in PLAN.values() for n in nums} - set(sections)
    if not sections.get("_preamble", "").strip():
        raise SystemExit("schema.sql: no CREATE EXTENSION statements found above section 0")
    if missing:
        raise SystemExit(f"schema.sql is missing expected sections: {sorted(missing)}")

    out = {}
    for name, (title, numbers) in PLAN.items():
        body = "\n\n".join(sections[n] for n in numbers)
        if 0 in numbers:
            body = sections["_preamble"] + "\n" + body
        out[name] = HEADER.format(name=name, title=title) + body
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    args = ap.parse_args()

    generated = build()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    drifted, written = [], []
    for name, content in generated.items():
        path = OUT_DIR / name
        if args.check:
            # Only committed migrations are checked; ones not yet landed are skipped.
            if path.exists() and path.read_text() != content:
                drifted.append(name)
        else:
            if not path.exists() or path.read_text() != content:
                path.write_text(content)
                written.append(name)

    if args.check:
        if drifted:
            print("build_migrations --check: FAILED — these have drifted from schema.sql:")
            for name in drifted:
                print(f"  - supabase/migrations/{name}")
            print("\nRegenerate with: python3 scripts/build_migrations.py")
            return 1
        present = [n for n in generated if (OUT_DIR / n).exists()]
        print(f"build_migrations --check: ok ({len(present)} migration(s) in sync with schema.sql)")
        return 0

    for name in written:
        print(f"  wrote supabase/migrations/{name}")
    if not written:
        print("  already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
