#!/usr/bin/env python3
"""Generate supabase/migrations/*.sql from docs/design/schema.sql.

    python3 scripts/build_migrations.py           # write only landed migration 0001
    python3 scripts/build_migrations.py --check   # fail if 0001 is missing or has drifted
    python3 scripts/build_migrations.py --target 0002_money.sql  # explicitly select future work

Repeat --target to select more than one migration. Future PLAN entries are never selected
implicitly. --check is read-only, including when the output directory does not exist.

`docs/design/schema.sql` is the single source of truth for the schema: it is the file reviewers read
alongside the design document. Hand-copying slices of it into migrations would guarantee the two
diverge within a month, so the migrations are generated and drift is a build failure.

The split is by the numbered banner sections in schema.sql, chosen so each migration can be reviewed
as one idea:

    0001_core   conventions + identity, events, participation
    0002_money  money tables, the functions that do the work, views, audit triggers
    0003_rls    every row-level security policy in one file

Phase-2 sections (9 hosted tournaments, 10 push/notifications) are not emitted yet; they become
0005 and 0004 when their milestones land. Generation is reproducible; executing a generated
migration is NOT replay-idempotent. Apply each migration once with a migration ledger. BEGIN/COMMIT
make a fresh installation atomic, rather than preserving half a schema after a failed statement.
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "design" / "schema.sql"
OUT_DIR = ROOT / "supabase" / "migrations"

# migration file -> (title, [section numbers from schema.sql])
PLAN = {
    "0001_core.sql": ("identity, events and participation", [0, 1, 2, 3]),
    "0002_money.sql": ("money, the functions that do the work, views and audit", [4, 5, 6, 8]),
    "0003_rls.sql": ("row-level security policies and role helpers", [7]),
}
LANDED_TARGETS = ("0001_core.sql",)

BANNER = re.compile(r"^--[ \t]+(\d+)\.[ \t]+\S.*$")
NUMBERED_COMMENT = re.compile(r"^--[ \t]*\d+(?:\.|[ \t]|$)")
SUBSECTION = re.compile(r"^--[ \t]+\d+\.\d+\b")
RULER = re.compile(r"^--[ \t]+[-=]{20,}[ \t]*$")
EXTENSION = re.compile(r"^\s*create\s+extension\b[^;]*;", re.IGNORECASE | re.MULTILINE)

HEADER = """-- =====================================================================
-- CalBlue — migration {name}
-- {title}
--
-- GENERATED from docs/design/schema.sql by scripts/build_migrations.py.
-- Do not edit this file directly: edit schema.sql and regenerate, or
-- scripts/build_migrations.py --check --target {name} will fail on drift.
-- Apply once with migration tracking; this SQL is not replay-idempotent.
-- =====================================================================

"""


class SchemaError(ValueError):
    """A source layout cannot be split safely into the requested migrations."""


def parse_sections(text):
    """Split schema.sql into {section_number: source_text}."""
    lines = text.splitlines()
    starts = []
    seen = set()
    for i, line in enumerate(lines):
        if SUBSECTION.match(line):
            continue
        match = BANNER.fullmatch(line)
        previous_is_ruler = i > 0 and RULER.fullmatch(lines[i - 1])
        if not match:
            if previous_is_ruler and NUMBERED_COMMENT.match(line):
                raise SchemaError(f"schema.sql:{i + 1}: malformed numbered section banner")
            continue
        if not previous_is_ruler:
            raise SchemaError(f"schema.sql:{i + 1}: section banner needs a preceding ruler")
        number = int(match.group(1))
        if number in seen:
            raise SchemaError(f"schema.sql:{i + 1}: duplicate section {number}")
        seen.add(number)
        starts.append((number, i - 1))

    if not starts:
        raise SchemaError("schema.sql: no numbered section banners found")
    numbers = [number for number, _ in starts]
    if numbers[0] != 0:
        raise SchemaError("schema.sql: section 0 must be the first numbered section")
    if numbers != sorted(numbers):
        raise SchemaError("schema.sql: numbered sections are out of order")
    missing = sorted(set(range(numbers[-1] + 1)) - seen)
    if missing:
        raise SchemaError(f"schema.sql: missing section banners: {missing}")

    sections = {}
    for idx, (number, start) in enumerate(starts):
        end = starts[idx + 1][1] if idx + 1 < len(starts) else len(lines)
        sections[number] = "\n".join(lines[start:end]).rstrip() + "\n"

    # Preserve the whole preamble, including comments and multiline/case-varied extension
    # statements. Silently dropping a line here could change the resulting installation.
    preamble = "\n".join(lines[:starts[0][1]]).strip()
    if not EXTENSION.search(preamble):
        raise SchemaError("schema.sql: no complete CREATE EXTENSION statement above section 0")
    sections["_preamble"] = preamble + "\n"
    return sections


def selected_targets(targets=None):
    requested = set(LANDED_TARGETS if targets is None else targets)
    if not requested:
        raise SchemaError("at least one migration target is required")
    unknown = requested - set(PLAN)
    if unknown:
        raise SchemaError(f"unknown migration targets: {sorted(unknown)}")
    return [name for name in PLAN if name in requested]


def build(targets=None, source_text=None):
    names = selected_targets(targets)
    if source_text is None:
        source_text = SOURCE.read_text(encoding="utf-8-sig")
    sections = parse_sections(source_text)
    missing = {n for name in names for n in PLAN[name][1]} - set(sections)
    if missing:
        raise SchemaError(f"schema.sql is missing required sections: {sorted(missing)}")

    out = {}
    for name in names:
        title, numbers = PLAN[name]
        body = "\n\n".join(sections[n].rstrip() for n in numbers)
        if 0 in numbers:
            body = sections["_preamble"] + "\n" + body
        out[name] = HEADER.format(name=name, title=title) + "BEGIN;\n\n" + body.rstrip() + "\n\nCOMMIT;\n"
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate only explicitly selected or landed migrations.")
    ap.add_argument("--check", action="store_true", help="read-only check; fail on missing files or drift")
    ap.add_argument("--target", action="append", choices=tuple(PLAN),
                    help="migration filename; repeat to select several (default: 0001_core.sql)")
    args = ap.parse_args(argv)

    try:
        generated = build(args.target)
    except (SchemaError, OSError, UnicodeError) as error:
        print(f"build_migrations: FAILED — {error}", file=sys.stderr)
        return 1

    problems, written = [], []
    for name, content in generated.items():
        path = OUT_DIR / name
        try:
            existing = path.read_bytes() if path.exists() else None
            if args.check:
                if existing is None:
                    problems.append(f"{name}: required migration is missing")
                elif existing != content.encode("utf-8"):
                    problems.append(f"{name}: has drifted from schema.sql")
            elif existing != content.encode("utf-8"):
                OUT_DIR.mkdir(parents=True, exist_ok=True)
                with path.open("w", encoding="utf-8", newline="\n") as stream:
                    stream.write(content)
                written.append(name)
        except OSError as error:
            problems.append(f"{name}: {error}")

    if problems:
        print("build_migrations: FAILED")
        for problem in problems:
            print(f"  - supabase/migrations/{problem}")
        targets = " ".join(f"--target {name}" for name in generated)
        print(f"\nRegenerate with: python3 scripts/build_migrations.py {targets}")
        return 1

    if args.check:
        print(f"build_migrations --check: ok ({len(generated)} required migration(s) in sync with schema.sql)")
        return 0

    for name in written:
        print(f"  wrote supabase/migrations/{name}")
    if not written:
        print("  already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
