-- =====================================================================
-- CalBlue — migration 0001_core.sql
-- identity, events and participation
--
-- GENERATED from docs/design/schema.sql by scripts/build_migrations.py.
-- Do not edit this file directly: edit schema.sql and regenerate, or
-- scripts/check_sql.py --check will fail on the drift.
-- =====================================================================

create extension if not exists pgcrypto;
create extension if not exists citext;

-- ---------------------------------------------------------------------
-- 0. Conventions
--   * every PK is a uuid, every table has created_at / updated_at
--   * status columns are text + CHECK, not enum types, so adding a state
--     is an ordinary migration rather than an ALTER TYPE dance
--   * money is numeric(10,2); it is exact, and the client formats it
--   * all instants are timestamptz (UTC); the *local* calendar date that
--     matters for billing is stored separately (see games.game_date)
-- ---------------------------------------------------------------------

create or replace function public.touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;


-- =====================================================================
-- 1. IDENTITY & ACCESS
-- =====================================================================

-- One row per login. Created automatically on sign-up.
create table public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  email         citext not null unique,
  display_name  text   not null default '',
  phone         text,
  -- Roles are additive: the same person is routinely a player, a coach and
  -- the point of contact for one tournament. Club-wide roles live here;
  -- roles that apply to only one competition or team live in role_grants.
  roles         text[] not null default '{}'
                check (roles <@ array['player','coach','referee','treasurer',
                                      'admin','developer']),
  locale        text   not null default 'en',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email,
          coalesce(new.raw_user_meta_data ->> 'display_name', ''))
  on conflict (id) do nothing;
  return new;
end $$;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();
revoke all on function public.handle_new_user() from public;

-- Mirror profiles.roles into the JWT so RLS can read them from the token
-- instead of re-querying profiles (which would make profiles policies
-- recursive). NOTE: the claim only changes when the token is refreshed —
-- after a promotion, the user must re-login or refresh.
create or replace function public.sync_role_claim() returns trigger
language plpgsql security definer set search_path = public, auth as $$
begin
  if tg_op = 'INSERT' or new.roles is distinct from old.roles then
    update auth.users
       set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb)
                               || jsonb_build_object('roles', to_jsonb(new.roles))
     where id = new.id;
  end if;
  return new;
end $$;

create trigger profiles_sync_roles after insert or update of roles on public.profiles
  for each row execute function public.sync_role_claim();
revoke all on function public.sync_role_claim() from public;


-- A person inside the club. Deliberately separate from `profiles`, but
-- **at most one identity per account** (see the unique index below):
--   * an account never has two identities, so nothing in the UI ever asks
--     "which of your identities is playing today?"
--   * an identity may exist with NO account at all — a drop-in guest, a
--     visiting player, or a name imported from the old roster sheet — and
--     be claimed later with claim_code
--   * a child is their own identity with no account, pointed at a parent by
--     guardian_account_id. The parent therefore still has exactly one
--     identity (their own) while acting for, and paying for, the children.
create table public.players (
  id                      uuid primary key default gen_random_uuid(),
  account_id              uuid references public.profiles(id) on delete set null,
  guardian_account_id     uuid references public.profiles(id) on delete set null,
  display_name            text not null,
  legal_name              text,
  date_of_birth           date,
  default_positions       text[] not null default '{}',   -- '{CM,CF}'
  preferred_number        int check (preferred_number between 0 and 99),
  jersey_size             text,
  photo_url               text,
  home_club_id            uuid references public.clubs(id) on delete set null,
  emergency_contact_name  text,
  emergency_contact_phone text,
  medical_notes           text,                           -- restricted, see RLS
  verification_status     text not null default 'pending'
                          check (verification_status in ('pending','verified','rejected')),
  verification_note       text,
  is_public               boolean not null default false, -- opt-in public roster
  claim_code              text unique,                    -- for unclaimed identities
  claimed_at              timestamptz,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  -- Who receives this person's charges: themselves, or their guardian if
  -- they have no login of their own. coalesce of two columns is immutable,
  -- so this can be stored and indexed.
  payer_account_id        uuid generated always as
                          (coalesce(account_id, guardian_account_id)) stored
  -- "a minor must have a guardian" is enforced in the application, not here:
  -- date_of_birth is optional and current_date is not immutable.
);
-- at most one identity per account (many NULLs are allowed: guests)
create unique index players_one_per_account on public.players(account_id)
  where account_id is not null;
create index players_guardian  on public.players(guardian_account_id);
create index players_payer     on public.players(payer_account_id);
create index players_public    on public.players(is_public)
  where is_public and verification_status = 'verified';
create trigger players_touch before update on public.players
  for each row execute function public.touch_updated_at();


-- =====================================================================
-- 2. EVENTS & SCHEDULE
-- =====================================================================

create table public.venues (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  address     text,
  map_url     text,
  surface     text check (surface in ('grass','turf','indoor','other')),
  timezone    text not null default 'America/Los_Angeles',   -- IANA
  notes       text,                                          -- parking, gate code
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger venues_touch before update on public.venues
  for each row execute function public.touch_updated_at();


-- An organisation. CalBlue is one row (is_us); every opponent and every
-- visiting side in a tournament we host is another. Cheap now, and it is what
-- lets section 9 exist at all without rewriting the fixture list.
create table public.clubs (
  id             uuid primary key default gen_random_uuid(),
  name           text not null,
  short_name     text,
  crest_url      text,
  city           text,
  contact_name   text,
  contact_email  citext,
  contact_phone  text,
  is_us          boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create unique index clubs_only_one_us on public.clubs(is_us) where is_us;

-- CalBlue currently fields one squad; this exists so that adding a B team, a
-- veterans side, or a visiting club's team is a row rather than a migration.
create table public.teams (
  id          uuid primary key default gen_random_uuid(),
  club_id     uuid not null references public.clubs(id) on delete restrict,
  name        text not null,
  short_name  text,
  age_group   text,
  is_default  boolean not null default false,   -- our primary squad
  created_at  timestamptz not null default now()
);
create index teams_by_club on public.teams(club_id);
create unique index teams_one_default on public.teams(is_default) where is_default;


create table public.competitions (
  id                     uuid primary key default gen_random_uuid(),
  name                   text not null,                       -- 'Kylin Cup'
  kind                   text not null
                         check (kind in ('league','tournament','cup','friendly_series')),
  season_label           text,                                -- '2026 Spring'
  organiser              text,                                -- 'UPSL', 'NCCSF'
  external_url           text,
  start_date             date,
  end_date               date,
  status                 text not null default 'draft'
                         check (status in ('draft','published','in_progress',
                                           'completed','archived','cancelled')),
  roster_approval        boolean not null default true,       -- admin must approve joiners
  -- 'participant' = we play in it (UPSL, NCCSF).
  -- 'host'        = we run it and other clubs enter (see section 9).
  hosting_mode           text not null default 'participant'
                         check (hosting_mode in ('participant','host')),
  entry_opens_at         timestamptz,
  entry_closes_at        timestamptz,
  entry_fee              numeric(10,2) check (entry_fee >= 0),
  max_teams              int check (max_teams > 0),
  rules_url              text,
  roster_public          boolean not null default false,
  points_win             int not null default 3,
  points_draw            int not null default 1,
  default_fee_per_game   numeric(10,2) check (default_fee_per_game >= 0),
  default_no_show_fee    numeric(10,2) check (default_no_show_fee >= 0),
  description            text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  check (end_date is null or start_date is null or end_date >= start_date)
);
create trigger competitions_touch before update on public.competitions
  for each row execute function public.touch_updated_at();


-- ONE table for every playable event: a league fixture, a tournament match,
-- a friendly, a pickup, a training session. `game_type` distinguishes them.
-- A pickup is exactly `game_type = 'pickup'` — never "competition_id is null",
-- because a friendly can also have no competition.
create table public.games (
  id                      uuid primary key default gen_random_uuid(),
  competition_id          uuid references public.competitions(id) on delete restrict,
  team_id                 uuid references public.teams(id),
  game_type               text not null
                          check (game_type in ('league','tournament','cup',
                                               'friendly','pickup','training')),
  title                   text not null,
  opponent                text,                        -- free text: 'San Ramon FC'
  home_away               text check (home_away in ('home','away','neutral')),
  -- for fixtures we run ourselves, both sides are real rows; for away games
  -- against a club we have not bothered to model, `opponent` is still fine
  home_team_id            uuid references public.teams(id) on delete restrict,
  away_team_id            uuid references public.teams(id) on delete restrict,
  stage_label             text,                        -- 'Group A', 'Semi-final'
  round_number            int,

  -- where
  venue_id                uuid references public.venues(id) on delete restrict,
  field_label             text,                        -- 'Turf 2', 'Field C'
  timezone                text not null default 'America/Los_Angeles',

  -- when
  gather_time             timestamptz,                 -- be at the field by
  start_time              timestamptz not null,        -- kick-off
  end_time                timestamptz,
  game_date               date not null,               -- local date, set by trigger

  -- logistics
  capacity                int check (capacity > 0),    -- null = unlimited
  min_players             int check (min_players > 0),
  waitlist_enabled        boolean not null default true,
  registration_opens_at   timestamptz,
  registration_closes_at  timestamptz,
  kit_color               text,
  notes                   text,

  -- money (null = inherit from competition, then fee_schedules, then 0)
  fee_override            numeric(10,2) check (fee_override >= 0),
  no_show_fee_override    numeric(10,2) check (no_show_fee_override >= 0),

  status                  text not null default 'draft'
                          check (status in ('draft','published','reg_closed',
                                            'completed','locked','cancelled')),
  cancellation_reason     text,
  attendance_locked_at    timestamptz,
  created_by              uuid references public.profiles(id),
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),

  check (end_time is null or end_time > start_time),
  check (gather_time is null or gather_time <= start_time),
  check (registration_closes_at is null or registration_closes_at <= start_time),
  -- a pickup or training session never belongs to a competition;
  -- a league/tournament/cup fixture always does
  check ((game_type in ('pickup','training')) = (competition_id is null)
         or game_type = 'friendly')
);
create index games_by_date   on public.games(game_date);
create index games_by_comp   on public.games(competition_id);
create index games_published on public.games(status, start_time)
  where status in ('published','reg_closed');

create or replace function public.set_game_date() returns trigger
language plpgsql as $$
begin
  new.game_date := (new.start_time at time zone new.timezone)::date;
  return new;
end $$;

create trigger games_set_date before insert or update of start_time, timezone
  on public.games for each row execute function public.set_game_date();
create trigger games_touch before update on public.games
  for each row execute function public.touch_updated_at();


-- Roles that apply to ONE thing rather than the whole club. The organiser of
-- the Kylin Cup is an organiser *of the Kylin Cup* — not a club-wide admin.
-- An account may hold any number of these at once, alongside its club-wide
-- roles in profiles.roles.
create table public.role_grants (
  id             uuid primary key default gen_random_uuid(),
  account_id     uuid not null references public.profiles(id) on delete cascade,
  role           text not null,
  competition_id uuid references public.competitions(id) on delete cascade,
  game_id        uuid references public.games(id) on delete cascade,
  team_id        uuid references public.teams(id) on delete cascade,
  granted_by     uuid references public.profiles(id),
  created_at     timestamptz not null default now(),
  constraint role_grant_allowed
    check (role in ('organiser','manager','captain','coach','treasurer')),
  constraint role_grant_scope_required
    check (competition_id is not null or game_id is not null
           or team_id is not null)
);
create index role_grants_by_account on public.role_grants(account_id);
create index role_grants_by_comp    on public.role_grants(competition_id);


-- =====================================================================
-- 3. PARTICIPATION
-- =====================================================================

-- Season eligibility: being on the roster makes you allowed to register for
-- that competition's games. It does not put you in any particular match.
create table public.competition_registrations (
  id              uuid primary key default gen_random_uuid(),
  competition_id  uuid not null references public.competitions(id) on delete cascade,
  player_id       uuid not null references public.players(id) on delete cascade,
  status          text not null default 'pending'
                  check (status in ('pending','approved','rejected','withdrawn')),
  jersey_number   int check (jersey_number between 0 and 99),
  positions       text[] not null default '{}',
  note            text,
  decided_by      uuid references public.profiles(id),
  decided_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (competition_id, player_id)
);
-- two players cannot wear the same number in the same competition
create unique index comp_reg_unique_number
  on public.competition_registrations(competition_id, jersey_number)
  where status = 'approved' and jersey_number is not null;
create trigger comp_reg_touch before update on public.competition_registrations
  for each row execute function public.touch_updated_at();


-- The per-game slot. This one row carries intent (status), identity for the
-- match (number, position) and outcome (attendance) — and it is the only
-- input to billing.
create table public.game_registrations (
  id             uuid primary key default gen_random_uuid(),
  game_id        uuid not null references public.games(id) on delete cascade,
  player_id      uuid not null references public.players(id) on delete restrict,

  status         text not null default 'registered'
                 check (status in ('registered','waitlisted','cancelled')),
  participation  text not null default 'player'
                 check (participation in ('player','keeper','coach','volunteer')),

  jersey_number  int check (jersey_number between 0 and 99),
  positions      text[] not null default '{}',

  attendance     text not null default 'unknown'
                 check (attendance in ('unknown','present','absent','excused')),
  checked_in_at  timestamptz,
  checked_in_by  uuid references public.profiles(id),

  registered_by  uuid references public.profiles(id),   -- self, guardian or admin
  registered_at  timestamptz not null default now(),
  cancelled_at   timestamptz,
  late_cancel    boolean not null default false,
  note           text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  unique (game_id, player_id),                           -- one slot per person
  check (attendance = 'unknown' or status <> 'waitlisted')
);
create index greg_by_game   on public.game_registrations(game_id)
  where status in ('registered','waitlisted');
create index greg_by_player on public.game_registrations(player_id);
create index greg_waitlist  on public.game_registrations(game_id, registered_at)
  where status = 'waitlisted';
create trigger greg_touch before update on public.game_registrations
  for each row execute function public.touch_updated_at();


-- Capacity is enforced in the database, under a per-game advisory lock, so
-- two people clicking "register" at the same moment cannot both get the last
-- slot. The application catches 'game_full' and offers the waitlist instead.
create or replace function public.enforce_game_capacity() returns trigger
language plpgsql as $$
declare cap int; taken int;
begin
  if new.status <> 'registered'
     or new.participation not in ('player','keeper') then
    return new;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(new.game_id::text, 0));

  select capacity into cap from public.games where id = new.game_id;
  if cap is null then
    return new;
  end if;

  select count(*) into taken
    from public.game_registrations
   where game_id = new.game_id
     and status = 'registered'
     and participation in ('player','keeper')
     and id <> new.id;

  if taken >= cap then
    raise exception 'game_full' using errcode = '23514';
  end if;
  return new;
end $$;

create trigger greg_capacity
  before insert or update of status, participation on public.game_registrations
  for each row execute function public.enforce_game_capacity();


-- When a slot frees up, promote the longest-waiting person. Guarded so the
-- cascade stops as soon as the game is full again.
create or replace function public.promote_from_waitlist(p_game uuid)
returns uuid
language plpgsql security definer set search_path = public as $$
declare cap int; taken int; promoted uuid;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_game::text, 0));

  select capacity into cap from public.games where id = p_game;
  if cap is null then
    return null;                        -- unlimited: nobody is ever waitlisted
  end if;

  select count(*) into taken
    from public.game_registrations
   where game_id = p_game and status = 'registered'
     and participation in ('player','keeper');

  if taken >= cap then
    return null;
  end if;

  update public.game_registrations
     set status = 'registered'
   where id = (select id from public.game_registrations
                where game_id = p_game and status = 'waitlisted'
                order by registered_at
                limit 1)
  returning id into promoted;

  return promoted;   -- caller (or a notification trigger) tells the player
end $$;

create or replace function public.on_slot_freed() returns trigger
language plpgsql as $$
begin
  if old.status = 'registered' and new.status <> 'registered' then
    perform public.promote_from_waitlist(new.game_id);
  end if;
  return null;
end $$;

create trigger greg_promote after update of status on public.game_registrations
  for each row execute function public.on_slot_freed();
revoke all on function public.promote_from_waitlist(uuid) from public;
