-- =====================================================================
-- CalBlue — migration 0002_money.sql
-- money, the functions that do the work, views and audit
--
-- GENERATED from docs/design/schema.sql by scripts/build_migrations.py.
-- Do not edit this file directly: edit schema.sql and regenerate, or
-- scripts/check_sql.py --check will fail on the drift.
-- =====================================================================

-- =====================================================================
-- 4. MONEY
-- =====================================================================

create table public.fee_schedules (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  competition_id  uuid references public.competitions(id) on delete cascade,
  game_type       text check (game_type in ('league','tournament','cup',
                                            'friendly','pickup','training')),
  amount          numeric(10,2) not null check (amount >= 0),
  effective_from  date not null default current_date,
  effective_to    date,
  created_at      timestamptz not null default now(),
  check (competition_id is not null or game_type is not null),
  check (effective_to is null or effective_to >= effective_from)
);


create table public.billing_periods (
  id          uuid primary key default gen_random_uuid(),
  label       text not null unique,                 -- '2026-Q1'
  start_date  date not null,
  end_date    date not null,
  status      text not null default 'open'
              check (status in ('open','preview','closed')),
  closed_at   timestamptz,
  closed_by   uuid references public.profiles(id),
  created_at  timestamptz not null default now(),
  check (end_date >= start_date)
);
-- periods must not overlap
alter table public.billing_periods
  add constraint billing_periods_no_overlap
  exclude using gist (daterange(start_date, end_date, '[]') with &&);


-- Immutable line items. A charge is written once, with the fee that applied
-- on the day — so changing a fee schedule next season never rewrites history.
-- Mistakes are voided (and re-issued), never edited or deleted.
create table public.charges (
  id                uuid primary key default gen_random_uuid(),
  -- nullable, because a tournament entry fee is owed by a club, not a person
  player_id         uuid references public.players(id) on delete restrict,
  account_id        uuid references public.profiles(id) on delete set null, -- payer at the time
  game_id           uuid references public.games(id) on delete restrict,
  competition_id    uuid references public.competitions(id) on delete set null,
  billing_period_id uuid references public.billing_periods(id) on delete set null,
  kind              text not null
                    check (kind in ('game_fee','season_dues','no_show','late_cancel',
                                    'equipment','adjustment','credit','entry_fee')),
  description       text not null,
  amount            numeric(10,2) not null check (amount <> 0),  -- negative = credit
  charge_date       date not null,
  source            text not null default 'auto' check (source in ('auto','manual')),
  created_by        uuid references public.profiles(id),
  created_at        timestamptz not null default now(),
  voided_at         timestamptz,
  voided_by         uuid references public.profiles(id),
  void_reason       text,
  -- set in section 9; every charge is owed by either a person or a team entry
  entry_id          uuid,
  check (player_id is not null or entry_id is not null)
);
-- makes attendance finalisation idempotent: re-running never double-charges
create unique index charges_auto_once on public.charges(game_id, player_id, kind)
  where source = 'auto' and voided_at is null and game_id is not null;
create index charges_by_player  on public.charges(player_id, charge_date);
create index charges_by_entry   on public.charges(entry_id);
create index charges_by_account on public.charges(account_id, charge_date);
create index charges_by_period  on public.charges(billing_period_id);

create or replace function public.charges_are_immutable() returns trigger
language plpgsql as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'charges cannot be deleted — void them instead';
  end if;
  if (new.player_id, new.game_id, new.kind, new.amount, new.charge_date)
     is distinct from
     (old.player_id, old.game_id, old.kind, old.amount, old.charge_date) then
    raise exception 'charges are immutable — void and re-issue instead';
  end if;
  return new;
end $$;

create trigger charges_immutable before update or delete on public.charges
  for each row execute function public.charges_are_immutable();


create table public.payments (
  id                uuid primary key default gen_random_uuid(),
  account_id        uuid not null references public.profiles(id) on delete restrict,
  player_id         uuid references public.players(id) on delete set null,  -- optional allocation
  billing_period_id uuid references public.billing_periods(id) on delete set null,
  amount            numeric(10,2) not null check (amount <> 0),  -- negative = refund
  method            text not null default 'other'
                    check (method in ('venmo','zelle','cash','check','card','other')),
  payment_date      date not null default current_date,
  external_ref      text,                       -- Venmo note, check number
  recorded_by       uuid references public.profiles(id),
  note              text,
  created_at        timestamptz not null default now()
);
create index payments_by_account on public.payments(account_id, payment_date);
create index payments_by_period  on public.payments(billing_period_id);


-- Frozen snapshots, written when a period is closed. Two grains, because
-- attendance is a property of a player and money is a property of a payer.
create table public.period_player_summaries (
  id                  uuid primary key default gen_random_uuid(),
  billing_period_id   uuid not null references public.billing_periods(id) on delete cascade,
  player_id           uuid not null references public.players(id),
  account_id          uuid references public.profiles(id),
  games_attended      int not null default 0,
  attended_league     int not null default 0,
  attended_tournament int not null default 0,
  attended_pickup     int not null default 0,
  attended_other      int not null default 0,
  no_shows            int not null default 0,
  late_cancels        int not null default 0,
  charges_total       numeric(10,2) not null default 0,
  created_at          timestamptz not null default now(),
  unique (billing_period_id, player_id)
);

create table public.period_account_summaries (
  id                uuid primary key default gen_random_uuid(),
  billing_period_id uuid not null references public.billing_periods(id) on delete cascade,
  account_id        uuid not null references public.profiles(id),
  opening_balance   numeric(10,2) not null default 0,
  charges_total     numeric(10,2) not null default 0,
  payments_total    numeric(10,2) not null default 0,
  closing_balance   numeric(10,2) not null default 0,
  created_at        timestamptz not null default now(),
  unique (billing_period_id, account_id)
);


create table public.audit_log (
  id         bigint generated always as identity primary key,
  actor_id   uuid references public.profiles(id),
  action     text not null,                   -- 'insert' | 'update' | 'delete' | 'break_glass'
  table_name text not null,
  row_id     text,
  before     jsonb,
  after      jsonb,
  created_at timestamptz not null default now()
);
create index audit_by_table on public.audit_log(table_name, created_at desc);


-- =====================================================================
-- 5. THE FOUR FUNCTIONS THAT DO THE WORK
-- =====================================================================

-- 5.1 What does this game cost a player? One definition, used by the
--     registration screen, the charge writer and the CSV export alike.
create or replace function public.resolve_game_fee(p_game uuid)
returns numeric
language sql stable as $$
  select coalesce(
    g.fee_override,
    c.default_fee_per_game,
    (select fs.amount
       from public.fee_schedules fs
      where (fs.competition_id = g.competition_id
             or (fs.competition_id is null and fs.game_type = g.game_type))
        and fs.effective_from <= g.game_date
        and (fs.effective_to is null or fs.effective_to >= g.game_date)
      order by (fs.competition_id is not null) desc, fs.effective_from desc
      limit 1),
    0)
  from public.games g
  left join public.competitions c on c.id = g.competition_id
  where g.id = p_game
$$;

create or replace function public.resolve_no_show_fee(p_game uuid)
returns numeric
language sql stable as $$
  select coalesce(g.no_show_fee_override, c.default_no_show_fee, 0)
  from public.games g
  left join public.competitions c on c.id = g.competition_id
  where g.id = p_game
$$;


-- 5.2 Close the game: anyone still 'unknown' did not turn up, then write the
--     line items. Safe to run twice — the partial unique index absorbs it.
create or replace function public.finalise_game_attendance(p_game uuid)
returns void
language plpgsql security definer set search_path = public as $$
declare v_fee numeric; v_no_show numeric; v_game public.games;
begin
  select * into v_game from public.games where id = p_game for update;
  if v_game is null then
    raise exception 'no such game %', p_game;
  end if;
  if v_game.status = 'cancelled' then
    return;                       -- a cancelled game never bills anybody
  end if;
  if v_game.attendance_locked_at is not null then
    raise exception 'attendance for this game is already locked';
  end if;

  update public.game_registrations
     set attendance = 'absent'
   where game_id = p_game
     and status = 'registered'
     and attendance = 'unknown';

  v_fee     := public.resolve_game_fee(p_game);
  v_no_show := public.resolve_no_show_fee(p_game);

  -- the game fee, for everyone who actually played
  insert into public.charges (player_id, account_id, game_id, competition_id,
                              kind, description, amount, charge_date, source)
  select gr.player_id, p.payer_account_id, p_game, v_game.competition_id,
         'game_fee', v_game.title, v_fee, v_game.game_date, 'auto'
    from public.game_registrations gr
    join public.players p on p.id = gr.player_id
   where gr.game_id = p_game
     and gr.attendance = 'present'
     and gr.participation in ('player','keeper')
     and v_fee > 0
  on conflict do nothing;

  -- the no-show fee, if the club charges one
  insert into public.charges (player_id, account_id, game_id, competition_id,
                              kind, description, amount, charge_date, source)
  select gr.player_id, p.payer_account_id, p_game, v_game.competition_id,
         'no_show', 'No-show: ' || v_game.title, v_no_show, v_game.game_date, 'auto'
    from public.game_registrations gr
    join public.players p on p.id = gr.player_id
   where gr.game_id = p_game
     and gr.attendance = 'absent'
     and gr.participation in ('player','keeper')
     and v_no_show > 0
  on conflict do nothing;

  update public.games
     set status = 'locked', attendance_locked_at = now()
   where id = p_game;
end $$;


-- 5.3 File every unassigned charge and payment into the period its date
--     falls in. Only touches open periods.
create or replace function public.assign_to_periods()
returns void
language sql security definer set search_path = public as $$
  with p as (select id, start_date, end_date from public.billing_periods
              where status <> 'closed')
  , c as (
    update public.charges ch set billing_period_id = p.id
      from p where ch.billing_period_id is null
       and ch.charge_date between p.start_date and p.end_date
    returning 1)
  update public.payments pay set billing_period_id = p.id
    from p where pay.billing_period_id is null
     and pay.payment_date between p.start_date and p.end_date;
$$;


-- 5.4 Close the quarter: freeze both snapshots. Refuses if any game in the
--     window still has unfinalised attendance, because that would silently
--     under-bill somebody.
create or replace function public.close_billing_period(p_period uuid)
returns void
language plpgsql security definer set search_path = public as $$
declare v public.billing_periods;
begin
  select * into v from public.billing_periods where id = p_period for update;
  if v.status = 'closed' then
    raise exception 'period % is already closed', v.label;
  end if;

  if exists (select 1 from public.games g
              where g.game_date between v.start_date and v.end_date
                and g.status not in ('locked','cancelled','draft')) then
    raise exception 'every game in % must be finalised or cancelled first', v.label;
  end if;

  perform public.assign_to_periods();

  with att as (
    select gr.player_id,
           count(*) filter (where gr.attendance = 'present') as present,
           count(*) filter (where gr.attendance = 'present'
                              and g.game_type = 'league') as league,
           count(*) filter (where gr.attendance = 'present'
                              and g.game_type in ('tournament','cup')) as tourn,
           count(*) filter (where gr.attendance = 'present'
                              and g.game_type = 'pickup') as pickup,
           count(*) filter (where gr.attendance = 'present'
                              and g.game_type in ('friendly','training')) as other,
           count(*) filter (where gr.attendance = 'absent') as no_shows,
           count(*) filter (where gr.late_cancel) as late_cancels
      from public.game_registrations gr
      join public.games g on g.id = gr.game_id
     where g.game_date between v.start_date and v.end_date
       and g.status <> 'cancelled'
     group by gr.player_id
  ), money as (
    select player_id, sum(amount) as total
      from public.charges
     where billing_period_id = p_period and voided_at is null
     group by player_id
  ), ids as (
    select player_id from att
    union
    select player_id from money
  )
  insert into public.period_player_summaries (
    billing_period_id, player_id, account_id, games_attended,
    attended_league, attended_tournament, attended_pickup, attended_other,
    no_shows, late_cancels, charges_total)
  select p_period, i.player_id, pl.payer_account_id,
         coalesce(a.present, 0), coalesce(a.league, 0), coalesce(a.tourn, 0),
         coalesce(a.pickup, 0), coalesce(a.other, 0), coalesce(a.no_shows, 0),
         coalesce(a.late_cancels, 0), coalesce(m.total, 0)
    from ids i
    join public.players pl on pl.id = i.player_id
    left join att   a on a.player_id = i.player_id
    left join money m on m.player_id = i.player_id;

  insert into public.period_account_summaries (
    billing_period_id, account_id, opening_balance,
    charges_total, payments_total, closing_balance)
  select p_period,
         a.id,
         coalesce(o.opening, 0),
         coalesce(c.total, 0),
         coalesce(pm.total, 0),
         coalesce(o.opening, 0) + coalesce(c.total, 0) - coalesce(pm.total, 0)
    from public.profiles a
    left join lateral (
      select coalesce(sum(ch.amount), 0)
             - coalesce((select sum(p2.amount) from public.payments p2
                          where p2.account_id = a.id and p2.payment_date < v.start_date), 0)
             as opening
        from public.charges ch
       where ch.account_id = a.id and ch.voided_at is null
         and ch.charge_date < v.start_date) o on true
    left join lateral (
      select sum(ch.amount) as total from public.charges ch
       where ch.account_id = a.id and ch.billing_period_id = p_period
         and ch.voided_at is null) c on true
    left join lateral (
      select sum(pay.amount) as total from public.payments pay
       where pay.account_id = a.id and pay.billing_period_id = p_period) pm on true
   where coalesce(o.opening, 0) <> 0
      or coalesce(c.total, 0) <> 0
      or coalesce(pm.total, 0) <> 0;

  update public.billing_periods
     set status = 'closed', closed_at = now(), closed_by = auth.uid()
   where id = p_period;
end $$;


-- =====================================================================
-- 6. VIEWS the app reads
-- =====================================================================

-- Live balance for an account, over all time. This is the number that
-- actually matters; the period snapshots are the paper trail behind it.
create or replace view public.v_account_balance as
select a.id as account_id,
       coalesce(c.total, 0) as charges_total,
       coalesce(p.total, 0) as payments_total,
       coalesce(c.total, 0) - coalesce(p.total, 0) as balance
  from public.profiles a
  left join lateral (select sum(amount) total from public.charges
                      where account_id = a.id and voided_at is null) c on true
  left join lateral (select sum(amount) total from public.payments
                      where account_id = a.id) p on true;

-- One statement line per charge or payment, for the "why do I owe this?" screen.
create or replace view public.v_account_ledger as
select account_id, charge_date as entry_date, kind as entry_type,
       description, amount, 'charge'::text as direction, id as source_id
  from public.charges where voided_at is null
union all
select account_id, payment_date, method,
       coalesce(note, 'Payment received'), -amount, 'payment', id
  from public.payments;

-- Public roster: opt-in only, verified only.
create or replace view public.v_public_roster as
select p.id, p.display_name, p.preferred_number, p.default_positions, p.photo_url
  from public.players p
 where p.is_public and p.verification_status = 'verified';


-- =====================================================================
-- 8. AUDIT
-- =====================================================================

create or replace function public.audit_row() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.audit_log (actor_id, action, table_name, row_id, before, after)
  values (auth.uid(), lower(tg_op), tg_table_name,
          coalesce(new.id, old.id)::text,
          case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
          case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end);
  return coalesce(new, old);
end $$;

create trigger audit_charges  after insert or update or delete on public.charges
  for each row execute function public.audit_row();
create trigger audit_payments after insert or update or delete on public.payments
  for each row execute function public.audit_row();
create trigger audit_profiles after update on public.profiles
  for each row execute function public.audit_row();
create trigger audit_periods  after update on public.billing_periods
  for each row execute function public.audit_row();
