-- =====================================================================
-- CalBlue — migration 0002_money.sql
-- money, the functions that do the work, views and audit
--
-- GENERATED from docs/design/schema.sql by scripts/build_migrations.py.
-- Do not edit this file directly: edit schema.sql and regenerate, or
-- scripts/build_migrations.py --check --target 0002_money.sql will fail on drift.
-- Apply once with migration tracking; this SQL is not replay-idempotent.
-- =====================================================================

BEGIN;

-- =====================================================================
-- 4. MONEY
-- =====================================================================

-- Issue #26 corrects the draft's incomplete immutability and locking rules.
-- This phase is intentionally deny-by-default: trusted SQL can exercise the
-- foundation, but no browser policy, money RPC grant or entry-fee UI exists yet.
-- A club-wide transaction lock favors correctness over write throughput. The
-- BEFORE STATEMENT triggers below acquire it before ordinary DML row locks;
-- finalization additionally takes the existing per-game registration lock.
-- Explicit owner locks/disabled triggers/DDL remain privileged maintenance and
-- are outside this protocol. Two-session concurrency still needs runtime tests.
-- An owner's direct call to 0001's promote_from_waitlist takes the per-game lock
-- first and can deadlock against this ordering; maintenance must retry an aborted
-- transaction. This phase does not rewrite that previously released helper.
create or replace function public.lock_billing() returns void
language plpgsql security definer set search_path = '' as $$
begin
  if current_setting('transaction_isolation') <> 'read committed' then
    raise exception 'billing_requires_read_committed' using errcode = '0A000';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('calblue:billing:v1', 0));
end $$;

create or replace function public.lock_billing_statement() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  perform public.lock_billing();
  if tg_op = 'TRUNCATE' then
    raise exception 'billing_truncate_forbidden' using errcode = '23514';
  end if;
  return null;
end $$;

create table public.fee_schedules (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  competition_id  uuid references public.competitions(id) on delete cascade,
  game_type       text check (game_type in ('league','tournament','cup',
                                            'friendly','pickup','training')),
  amount          numeric(10,2) not null check (amount >= 0 and amount <> 'NaN'::numeric),
  effective_from  date not null default current_date,
  effective_to    date,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  check (competition_id is not null or game_type is not null),
  check (effective_to is null or effective_to >= effective_from)
);
create trigger fee_schedules_touch before update on public.fee_schedules
  for each row execute function public.touch_updated_at();


create table public.billing_periods (
  id          uuid primary key default gen_random_uuid(),
  label       text not null unique,                 -- '2026-Q1'
  start_date  date not null,
  end_date    date not null,
  status      text not null default 'open'
              check (status in ('open','preview','closed')),
  closed_at   timestamptz,
  closed_by   uuid references public.profiles(id),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  check (end_date >= start_date),
  check ((status = 'closed') = (closed_at is not null)),
  check (status = 'closed' or closed_by is null)
);
-- periods must not overlap
alter table public.billing_periods
  add constraint billing_periods_no_overlap
  exclude using gist (daterange(start_date, end_date, '[]') with &&);
create trigger billing_periods_touch before update on public.billing_periods
  for each row execute function public.touch_updated_at();

-- The latest closed end date also seals earlier gaps: a newly backdated entry
-- in a gap would otherwise change an already-issued opening balance.
create or replace function public.require_open_billing_date(p_date date, p_period uuid)
returns void
language plpgsql security definer set search_path = '' as $$
declare cutoff date; period_row public.billing_periods;
begin
  perform public.lock_billing();
  if p_date is null then
    raise exception 'billing_date_required' using errcode = '23514';
  end if;
  select max(end_date) into cutoff from public.billing_periods where status = 'closed';
  if p_date <= cutoff then
    raise exception 'billing_history_closed' using errcode = '23514';
  end if;
  if p_period is not null then
    select * into period_row from public.billing_periods where id = p_period;
    if not found then
      raise exception 'billing_period_not_found' using errcode = '23503';
    end if;
    if period_row.status = 'closed' then
      raise exception 'billing_period_is_closed' using errcode = '23514';
    end if;
    if p_date not between period_row.start_date and period_row.end_date then
      raise exception 'billing_period_date_mismatch' using errcode = '23514';
    end if;
  end if;
end $$;


-- Immutable line items. A charge is written once, with the fee that applied
-- on the day — so changing a fee schedule next season never rewrites history.
-- Mistakes are voided (and re-issued), never edited or deleted.
create table public.charges (
  id                uuid primary key default gen_random_uuid(),
  -- nullable, because a tournament entry fee is owed by a club, not a person
  player_id         uuid references public.players(id) on delete restrict,
  account_id        uuid references public.profiles(id) on delete restrict, -- payer at the time
  game_id           uuid references public.games(id) on delete restrict,
  competition_id    uuid references public.competitions(id) on delete restrict,
  billing_period_id uuid references public.billing_periods(id) on delete restrict,
  kind              text not null
                    check (kind in ('game_fee','season_dues','no_show','late_cancel',
                                    'equipment','adjustment','credit','entry_fee')),
  description       text not null,
  amount            numeric(10,2) not null check (amount <> 0 and amount <> 'NaN'::numeric), -- negative = credit
  charge_date       date not null,
  source            text not null default 'auto' check (source in ('auto','manual')),
  created_by        uuid references public.profiles(id),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  voided_at         timestamptz,
  voided_by         uuid references public.profiles(id),
  void_reason       text,
  -- Exactly one subject. The entry FK and validation arrive with section 9;
  -- this forward-compatible column is not an authorized entry-fee workflow.
  entry_id          uuid,
  check (num_nonnulls(player_id, entry_id) = 1),
  check ((voided_at is null and voided_by is null and void_reason is null)
         or (voided_at is not null and nullif(btrim(void_reason), '') is not null))
);
-- makes attendance finalisation idempotent: re-running never double-charges
create unique index charges_auto_once on public.charges(game_id, player_id, kind)
  where source = 'auto' and voided_at is null and game_id is not null;
create index charges_by_player  on public.charges(player_id, charge_date);
create index charges_by_entry   on public.charges(entry_id);
create index charges_by_account on public.charges(account_id, charge_date);
create index charges_by_period  on public.charges(billing_period_id);

create or replace function public.charges_are_immutable() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'charges_are_immutable' using errcode = '23514';
  end if;
  perform public.require_open_billing_date(new.charge_date, new.billing_period_id);
  if tg_op = 'INSERT' then
    if new.voided_at is not null or new.voided_by is not null or new.void_reason is not null then
      raise exception 'charge_void_requires_update' using errcode = '23514';
    end if;
    return new;
  end if;
  -- Compare all present/future columns except the explicitly permitted fields.
  if (to_jsonb(new) - array['updated_at','billing_period_id','voided_at','voided_by','void_reason'])
     is distinct from
     (to_jsonb(old) - array['updated_at','billing_period_id','voided_at','voided_by','void_reason']) then
    raise exception 'charges_are_immutable' using errcode = '23514';
  end if;
  if old.billing_period_id is not null
     and new.billing_period_id is distinct from old.billing_period_id then
    raise exception 'billing_period_assignment_immutable' using errcode = '23514';
  end if;
  if old.voided_at is not null then
    if (new.voided_at, new.voided_by, new.void_reason)
       is distinct from (old.voided_at, old.voided_by, old.void_reason) then
      raise exception 'charge_void_is_final' using errcode = '23514';
    end if;
  elsif new.voided_at is not null then
    if nullif(btrim(new.void_reason), '') is null then
      raise exception 'charge_void_reason_required' using errcode = '23514';
    end if;
  elsif new.voided_by is not null or new.void_reason is not null then
    raise exception 'charge_void_reason_required' using errcode = '23514';
  end if;
  return new;
end $$;

create trigger charges_immutable before update or delete on public.charges
  for each row execute function public.charges_are_immutable();
create trigger charges_validate_insert before insert on public.charges
  for each row execute function public.charges_are_immutable();
create trigger charges_touch before update on public.charges
  for each row execute function public.touch_updated_at();


create table public.payments (
  id                uuid primary key default gen_random_uuid(),
  account_id        uuid not null references public.profiles(id) on delete restrict,
  player_id         uuid references public.players(id) on delete restrict,  -- optional allocation
  billing_period_id uuid references public.billing_periods(id) on delete restrict,
  amount            numeric(10,2) not null check (amount <> 0 and amount <> 'NaN'::numeric), -- negative = refund
  method            text not null default 'other'
                    check (method in ('venmo','zelle','cash','check','card','other')),
  payment_date      date not null default current_date,
  external_ref      text,                       -- Venmo note, check number
  recorded_by       uuid references public.profiles(id),
  note              text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index payments_by_account on public.payments(account_id, payment_date);
create index payments_by_period  on public.payments(billing_period_id);

-- Payments are facts too: corrections use a refund/replacement, not a rewrite.
create or replace function public.payments_are_immutable() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'payments_are_immutable' using errcode = '23514';
  end if;
  perform public.require_open_billing_date(new.payment_date, new.billing_period_id);
  if tg_op = 'UPDATE' then
    if (to_jsonb(new) - array['updated_at','billing_period_id'])
       is distinct from (to_jsonb(old) - array['updated_at','billing_period_id']) then
      raise exception 'payments_are_immutable' using errcode = '23514';
    end if;
    if old.billing_period_id is not null
       and new.billing_period_id is distinct from old.billing_period_id then
      raise exception 'billing_period_assignment_immutable' using errcode = '23514';
    end if;
  end if;
  return new;
end $$;
create trigger payments_immutable before insert or update or delete on public.payments
  for each row execute function public.payments_are_immutable();
create trigger payments_touch before update on public.payments
  for each row execute function public.touch_updated_at();


-- Frozen snapshots, written when a period is closed. Two grains, because
-- attendance is a property of a player and money is a property of a payer.
create table public.period_player_summaries (
  id                  uuid primary key default gen_random_uuid(),
  billing_period_id   uuid not null references public.billing_periods(id) on delete restrict,
  player_id           uuid not null references public.players(id),
  account_id          uuid references public.profiles(id),
  games_attended      int not null default 0,
  attended_league     int not null default 0,
  attended_tournament int not null default 0,
  attended_pickup     int not null default 0,
  attended_other      int not null default 0,
  no_shows            int not null default 0,
  late_cancels        int not null default 0,
  charges_total       numeric(10,2) not null default 0,
  created_at          timestamptz not null default now(),
  unique (billing_period_id, player_id)
);

create table public.period_account_summaries (
  id                uuid primary key default gen_random_uuid(),
  billing_period_id uuid not null references public.billing_periods(id) on delete restrict,
  account_id        uuid not null references public.profiles(id),
  opening_balance   numeric(10,2) not null default 0,
  charges_total     numeric(10,2) not null default 0,
  payments_total    numeric(10,2) not null default 0,
  closing_balance   numeric(10,2) not null default 0,
  created_at        timestamptz not null default now(),
  unique (billing_period_id, account_id)
);


create table public.audit_log (
  id         bigint generated always as identity primary key,
  actor_id   uuid references public.profiles(id),
  action     text not null,                   -- 'insert' | 'update' | 'delete' | 'break_glass'
  table_name text not null,
  row_id     text,
  before     jsonb,
  after      jsonb,
  created_at timestamptz not null default now()
);
create index audit_by_table on public.audit_log(table_name, created_at desc);

create or replace function public.guard_billing_period() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  perform public.lock_billing();
  if tg_op <> 'INSERT' and old.status = 'closed' then
    raise exception 'billing_period_is_closed' using errcode = '23514';
  end if;
  if tg_op = 'DELETE' then
    return old;
  end if;
  if tg_op = 'INSERT' then
    if new.status = 'closed' then
      raise exception 'billing_period_cannot_start_closed' using errcode = '23514';
    end if;
  else
    if (new.id, new.start_date, new.end_date, new.created_at)
       is distinct from (old.id, old.start_date, old.end_date, old.created_at) then
      raise exception 'billing_period_dates_immutable' using errcode = '23514';
    end if;
  end if;
  perform public.require_open_billing_date(new.start_date, null);
  if new.status = 'closed' then
    -- All ordinary status transitions, even direct trusted SQL updates, run
    -- exactly the same closure checks and snapshot writer. No client-settable
    -- session flag is accepted as evidence that closure was authorized.
    perform public.write_billing_period_summaries(old.id);
    new.closed_at := now();
    new.closed_by := auth.uid();
  elsif new.closed_at is not null or new.closed_by is not null then
    raise exception 'billing_period_not_closed' using errcode = '23514';
  end if;
  return new;
end $$;
create trigger billing_periods_guard before insert or update or delete on public.billing_periods
  for each row execute function public.guard_billing_period();

create or replace function public.freeze_billing_history() returns trigger
language plpgsql security definer set search_path = '' as $$
declare period_status text;
begin
  if tg_op <> 'INSERT' then
    raise exception 'billing_history_is_immutable' using errcode = '23514';
  end if;
  select status into period_status from public.billing_periods where id = new.billing_period_id;
  if not found then
    raise exception 'billing_period_not_found' using errcode = '23503';
  end if;
  if period_status = 'closed' then
    raise exception 'billing_period_is_closed' using errcode = '23514';
  end if;
  return new;
end $$;
create trigger player_summaries_frozen before insert or update or delete on public.period_player_summaries
  for each row execute function public.freeze_billing_history();
create trigger account_summaries_frozen before insert or update or delete on public.period_account_summaries
  for each row execute function public.freeze_billing_history();
create trigger audit_log_frozen before update or delete on public.audit_log
  for each row execute function public.freeze_billing_history();

-- These add guards rather than redefining any function released in 0001.
create or replace function public.guard_billed_game() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if tg_op <> 'INSERT' and (old.status = 'locked' or old.attendance_locked_at is not null) then
    if tg_op = 'DELETE' then
      raise exception 'game_attendance_is_locked' using errcode = '23514';
    end if;
    if (new.id, new.competition_id, new.game_type, new.start_time, new.timezone,
        new.venue_id, new.game_date, new.fee_override, new.no_show_fee_override,
        new.status, new.attendance_locked_at)
       is distinct from
       (old.id, old.competition_id, old.game_type, old.start_time, old.timezone,
        old.venue_id, old.game_date, old.fee_override, old.no_show_fee_override,
        old.status, old.attendance_locked_at) then
      raise exception 'game_attendance_is_locked' using errcode = '23514';
    end if;
  end if;
  if tg_op = 'DELETE' then
    if old.status <> 'draft' then
      perform public.require_open_billing_date(old.game_date, null);
    end if;
    return old;
  end if;
  if new.status = 'locked' and (tg_op = 'INSERT' or old.status <> 'locked') then
    if tg_op = 'INSERT' then
      raise exception 'game_cannot_start_locked' using errcode = '23514';
    end if;
    if old.status <> 'completed' then
      raise exception 'game_must_be_completed' using errcode = '23514';
    end if;
    if (new.id, new.competition_id, new.game_type, new.start_time, new.timezone,
        new.venue_id, new.game_date, new.fee_override, new.no_show_fee_override)
       is distinct from
       (old.id, old.competition_id, old.game_type, old.start_time, old.timezone,
        old.venue_id, old.game_date, old.fee_override, old.no_show_fee_override) then
      raise exception 'game_finalisation_cannot_change_facts' using errcode = '23514';
    end if;
    perform public.write_game_attendance_charges(old.id);
    new.attendance_locked_at := now();
  end if;
  if (new.status = 'locked') <> (new.attendance_locked_at is not null) then
    raise exception 'game_attendance_lock_mismatch' using errcode = '23514';
  end if;
  -- Drafts deliberately do not block period closure. They cannot subsequently
  -- become published/completed historical games inside the sealed date range.
  if new.status <> 'draft' then
    if tg_op = 'INSERT' or old.status <> 'locked' then
      perform public.require_open_billing_date(new.game_date, null);
    end if;
  end if;
  if tg_op = 'UPDATE' and old.status not in ('draft','locked') then
    perform public.require_open_billing_date(old.game_date, null);
  end if;
  return new;
end $$;
-- Alphabetical ordering runs this after 0001's games_set_date trigger.
create trigger games_z_billing_guard before insert or update or delete on public.games
  for each row execute function public.guard_billed_game();

create or replace function public.guard_billed_registration() returns trigger
language plpgsql security definer set search_path = '' as $$
declare game_row public.games; target_game uuid;
begin
  target_game := case when tg_op = 'DELETE' then old.game_id else new.game_id end;
  select * into game_row from public.games where id = target_game;
  if not found then
    -- A parent-game DELETE may already hide its row in an FK cascade; the
    -- game guard checked that deletion before this child operation began.
    return case when tg_op = 'DELETE' then old else new end;
  end if;
  if game_row.status = 'locked' or game_row.attendance_locked_at is not null then
    if tg_op <> 'UPDATE' then
      raise exception 'game_attendance_is_locked' using errcode = '23514';
    end if;
    if (new.game_id, new.player_id, new.status, new.participation,
        new.attendance, new.checked_in_at, new.checked_in_by, new.late_cancel)
       is distinct from
       (old.game_id, old.player_id, old.status, old.participation,
        old.attendance, old.checked_in_at, old.checked_in_by, old.late_cancel) then
      raise exception 'game_attendance_is_locked' using errcode = '23514';
    end if;
  elsif game_row.status <> 'draft' then
    perform public.require_open_billing_date(game_row.game_date, null);
  end if;
  return case when tg_op = 'DELETE' then old else new end;
end $$;
create trigger greg_billing_guard before insert or update or delete on public.game_registrations
  for each row execute function public.guard_billed_registration();

create trigger fee_schedules_billing_lock before insert or update or delete or truncate on public.fee_schedules
  for each statement execute function public.lock_billing_statement();
create trigger billing_periods_billing_lock before insert or update or delete or truncate on public.billing_periods
  for each statement execute function public.lock_billing_statement();
create trigger charges_billing_lock before insert or update or delete or truncate on public.charges
  for each statement execute function public.lock_billing_statement();
create trigger payments_billing_lock before insert or update or delete or truncate on public.payments
  for each statement execute function public.lock_billing_statement();
create trigger player_summaries_billing_lock before insert or update or delete or truncate on public.period_player_summaries
  for each statement execute function public.lock_billing_statement();
create trigger account_summaries_billing_lock before insert or update or delete or truncate on public.period_account_summaries
  for each statement execute function public.lock_billing_statement();
create trigger audit_log_billing_lock before insert or update or delete or truncate on public.audit_log
  for each statement execute function public.lock_billing_statement();
create trigger games_billing_lock before insert or update or delete or truncate on public.games
  for each statement execute function public.lock_billing_statement();
create trigger greg_billing_lock before insert or update or delete or truncate on public.game_registrations
  for each statement execute function public.lock_billing_statement();
create trigger players_billing_lock before insert or update or delete or truncate on public.players
  for each statement execute function public.lock_billing_statement();
create trigger competitions_billing_lock before insert or update or delete or truncate on public.competitions
  for each statement execute function public.lock_billing_statement();
create trigger profiles_billing_lock before insert or update or delete or truncate on public.profiles
  for each statement execute function public.lock_billing_statement();

-- =====================================================================
-- 5. BILLING FUNCTIONS AND INTERNAL WRITERS
-- =====================================================================

-- 5.1 What does this game cost a player? One definition, used by the
--     registration screen, the charge writer and the CSV export alike.
create or replace function public.resolve_game_fee(p_game uuid)
returns numeric
language sql stable set search_path = '' as $$
  select coalesce(
    g.fee_override,
    c.default_fee_per_game,
    (select fs.amount
       from public.fee_schedules fs
      where (fs.competition_id = g.competition_id
             or (fs.competition_id is null and fs.game_type = g.game_type))
        and (fs.game_type is null or fs.game_type = g.game_type)
        and fs.effective_from <= g.game_date
        and (fs.effective_to is null or fs.effective_to >= g.game_date)
      order by (fs.competition_id is not null) desc, fs.effective_from desc,
               fs.created_at desc, fs.id
      limit 1),
    0)
  from public.games g
  left join public.competitions c on c.id = g.competition_id
  where g.id = p_game
$$;

create or replace function public.resolve_no_show_fee(p_game uuid)
returns numeric
language sql stable set search_path = '' as $$
  select coalesce(g.no_show_fee_override, c.default_no_show_fee, 0)
  from public.games g
  left join public.competitions c on c.id = g.competition_id
  where g.id = p_game
$$;


-- 5.2 The game guard calls this private writer before moving completed→locked.
--     Direct owner status updates therefore cannot silently skip billing.
create or replace function public.write_game_attendance_charges(p_game uuid)
returns void
language plpgsql security definer set search_path = '' as $$
declare v_fee numeric; v_no_show numeric; v_game public.games;
begin
  perform public.lock_billing();
  perform pg_advisory_xact_lock(hashtextextended(p_game::text, 0));
  select * into v_game from public.games where id = p_game for update;
  if not found then
    raise exception 'game_not_found' using errcode = '23503';
  end if;
  if v_game.status in ('cancelled','locked') then
    return;
  end if;
  if v_game.status <> 'completed' then
    raise exception 'game_must_be_completed' using errcode = '23514';
  end if;
  perform public.require_open_billing_date(v_game.game_date, null);

  update public.game_registrations
     set attendance = 'absent'
   where game_id = p_game
     and status = 'registered'
     and participation in ('player','keeper')
     and attendance = 'unknown';

  v_fee     := public.resolve_game_fee(p_game);
  v_no_show := public.resolve_no_show_fee(p_game);

  -- the game fee, for everyone who actually played
  insert into public.charges (player_id, account_id, game_id, competition_id,
                              kind, description, amount, charge_date, source)
  select gr.player_id, p.payer_account_id, p_game, v_game.competition_id,
         'game_fee', v_game.title, v_fee, v_game.game_date, 'auto'
    from public.game_registrations gr
    join public.players p on p.id = gr.player_id
   where gr.game_id = p_game
     and gr.attendance = 'present'
     and gr.status = 'registered'
     and gr.participation in ('player','keeper')
     and v_fee > 0
  on conflict (game_id, player_id, kind)
    where source = 'auto' and voided_at is null and game_id is not null
    do nothing;

  -- the no-show fee, if the club charges one
  insert into public.charges (player_id, account_id, game_id, competition_id,
                              kind, description, amount, charge_date, source)
  select gr.player_id, p.payer_account_id, p_game, v_game.competition_id,
         'no_show', 'No-show: ' || v_game.title, v_no_show, v_game.game_date, 'auto'
    from public.game_registrations gr
    join public.players p on p.id = gr.player_id
   where gr.game_id = p_game
     and gr.attendance = 'absent'
     and gr.status = 'registered'
     and gr.participation in ('player','keeper')
     and v_no_show > 0
  on conflict (game_id, player_id, kind)
    where source = 'auto' and voided_at is null and game_id is not null
    do nothing;
end $$;

-- Retrying a successful finalization is a no-op, including after its period
-- closes. The private writer and partial unique index are defense in depth.
create or replace function public.finalise_game_attendance(p_game uuid)
returns void
language plpgsql security definer set search_path = '' as $$
declare game_status text;
begin
  perform public.lock_billing();
  perform pg_advisory_xact_lock(hashtextextended(p_game::text, 0));
  select status into game_status from public.games where id = p_game for update;
  if not found then
    raise exception 'game_not_found' using errcode = '23503';
  end if;
  if game_status in ('cancelled','locked') then
    return;
  end if;
  if game_status <> 'completed' then
    raise exception 'game_must_be_completed' using errcode = '23514';
  end if;
  update public.games
     set status = 'locked', attendance_locked_at = now()
   where id = p_game;
end $$;


-- 5.3 File every unassigned charge and payment into the period its date
--     falls in. Only touches open periods.
create or replace function public.assign_to_periods()
returns void
language plpgsql security definer set search_path = '' as $$
begin
  perform public.lock_billing();
  update public.charges ch set billing_period_id = p.id
    from public.billing_periods p
   where ch.billing_period_id is null and p.status <> 'closed'
     and ch.charge_date between p.start_date and p.end_date;
  update public.payments pay set billing_period_id = p.id
    from public.billing_periods p
   where pay.billing_period_id is null and p.status <> 'closed'
     and pay.payment_date between p.start_date and p.end_date;
end $$;


-- 5.4 Close the quarter: freeze both snapshots. Refuses if any game in the
--     window still has unfinalised attendance, because that would silently
--     under-bill somebody.
-- Private snapshot writer used by the period guard. The guard, rather than a
-- forgeable GUC or an assumption about the caller, makes every close transition
-- execute these checks. Only the owner may insert snapshots in this phase;
-- future client grants for snapshots must remain SELECT-only.
create or replace function public.write_billing_period_summaries(p_period uuid)
returns void
language plpgsql security definer set search_path = '' as $$
declare v public.billing_periods;
begin
  perform public.lock_billing();
  select * into v from public.billing_periods where id = p_period for update;
  if not found then
    raise exception 'billing_period_not_found' using errcode = '23503';
  end if;
  if v.status = 'closed' then
    raise exception 'billing_period_is_closed' using errcode = '23514';
  end if;
  if exists (select 1 from public.billing_periods
              where id <> p_period and start_date < v.start_date and status <> 'closed')
     or exists (select 1 from public.billing_periods
                 where status = 'closed' and end_date >= v.start_date) then
    raise exception 'billing_period_close_out_of_order' using errcode = '23514';
  end if;
  if exists (select 1 from public.period_player_summaries where billing_period_id = p_period)
     or exists (select 1 from public.period_account_summaries where billing_period_id = p_period) then
    raise exception 'billing_period_snapshots_already_exist' using errcode = '23514';
  end if;

  if exists (select 1 from public.games g
              where g.game_date between v.start_date and v.end_date
                and g.status not in ('locked','cancelled','draft')) then
    raise exception 'billing_period_has_unfinalised_games' using errcode = '23514';
  end if;

  perform public.assign_to_periods();

  with att as (
    select gr.player_id,
           count(*) filter (where gr.status = 'registered' and gr.attendance = 'present') as present,
           count(*) filter (where gr.status = 'registered' and gr.attendance = 'present'
                              and g.game_type = 'league') as league,
           count(*) filter (where gr.status = 'registered' and gr.attendance = 'present'
                              and g.game_type in ('tournament','cup')) as tourn,
           count(*) filter (where gr.status = 'registered' and gr.attendance = 'present'
                              and g.game_type = 'pickup') as pickup,
           count(*) filter (where gr.status = 'registered' and gr.attendance = 'present'
                              and g.game_type in ('friendly','training')) as other,
           count(*) filter (where gr.status = 'registered' and gr.attendance = 'absent') as no_shows,
           count(*) filter (where gr.status = 'cancelled' and gr.late_cancel) as late_cancels
      from public.game_registrations gr
      join public.games g on g.id = gr.game_id
     where g.game_date between v.start_date and v.end_date
       -- Drafts are not played obligations. Cancelled games never contribute;
       -- only finalized registered players/keepers count toward attendance.
       and g.status = 'locked'
       and gr.participation in ('player','keeper')
       and (gr.status = 'registered' or (gr.status = 'cancelled' and gr.late_cancel))
     group by gr.player_id
  ), money as (
    select player_id, sum(amount) as total
      from public.charges
     where billing_period_id = p_period and voided_at is null and player_id is not null
     group by player_id
  ), ids as (
    select player_id from att
    union
    select player_id from money
  )
  insert into public.period_player_summaries (
    billing_period_id, player_id, account_id, games_attended,
    attended_league, attended_tournament, attended_pickup, attended_other,
    no_shows, late_cancels, charges_total)
  select p_period, i.player_id, pl.payer_account_id,
         coalesce(a.present, 0), coalesce(a.league, 0), coalesce(a.tourn, 0),
         coalesce(a.pickup, 0), coalesce(a.other, 0), coalesce(a.no_shows, 0),
         coalesce(a.late_cancels, 0), coalesce(m.total, 0)
    from ids i
    join public.players pl on pl.id = i.player_id
    left join att   a on a.player_id = i.player_id
    left join money m on m.player_id = i.player_id;

  insert into public.period_account_summaries (
    billing_period_id, account_id, opening_balance,
    charges_total, payments_total, closing_balance)
  select p_period,
         a.id,
         coalesce(o.opening, 0),
         coalesce(c.total, 0),
         coalesce(pm.total, 0),
         coalesce(o.opening, 0) + coalesce(c.total, 0) - coalesce(pm.total, 0)
    from public.profiles a
    left join lateral (
      select coalesce(sum(ch.amount), 0)
             - coalesce((select sum(p2.amount) from public.payments p2
                          where p2.account_id = a.id and p2.payment_date < v.start_date), 0)
             as opening
        from public.charges ch
       where ch.account_id = a.id and ch.voided_at is null
         and ch.charge_date < v.start_date) o on true
    left join lateral (
      select sum(ch.amount) as total from public.charges ch
       where ch.account_id = a.id and ch.billing_period_id = p_period
         and ch.voided_at is null) c on true
    left join lateral (
      select sum(pay.amount) as total from public.payments pay
       where pay.account_id = a.id and pay.billing_period_id = p_period) pm on true
   where coalesce(o.opening, 0) <> 0
      or coalesce(c.total, 0) <> 0
      or coalesce(pm.total, 0) <> 0;

end $$;

create or replace function public.close_billing_period(p_period uuid)
returns void
language plpgsql security definer set search_path = '' as $$
declare period_status text;
begin
  perform public.lock_billing();
  select status into period_status from public.billing_periods where id = p_period for update;
  if not found then
    raise exception 'billing_period_not_found' using errcode = '23503';
  end if;
  if period_status = 'closed' then
    raise exception 'billing_period_is_closed' using errcode = '23514';
  end if;
  -- The guard writes both snapshots before this state transition completes.
  update public.billing_periods set status = 'closed' where id = p_period;
end $$;

-- =====================================================================
-- 6. VIEWS the app reads
-- =====================================================================

-- Live balance for an account, over all time. This is the number that
-- actually matters; the period snapshots are the paper trail behind it.
create or replace view public.v_account_balance with (security_invoker = true) as
select a.id as account_id,
       coalesce(c.total, 0) as charges_total,
       coalesce(p.total, 0) as payments_total,
       coalesce(c.total, 0) - coalesce(p.total, 0) as balance
  from public.profiles a
  left join lateral (select sum(amount) total from public.charges
                      where account_id = a.id and voided_at is null) c on true
  left join lateral (select sum(amount) total from public.payments
                      where account_id = a.id) p on true;

-- One statement line per charge or payment, for the "why do I owe this?" screen.
create or replace view public.v_account_ledger with (security_invoker = true) as
select account_id, charge_date as entry_date, kind as entry_type,
       description, amount, 'charge'::text as direction, id as source_id
  from public.charges where voided_at is null
union all
select account_id, payment_date, method,
       coalesce(note, 'Payment received'), -amount, 'payment', id
  from public.payments;

-- Public roster: opt-in only, verified only.
create or replace view public.v_public_roster with (security_invoker = true) as
select p.id, p.display_name, p.preferred_number, p.default_positions, p.photo_url
  from public.players p
 where p.is_public and p.verification_status = 'verified';

-- =====================================================================
-- 8. AUDIT
-- =====================================================================

create or replace function public.audit_row() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.audit_log (actor_id, action, table_name, row_id, before, after)
  values (auth.uid(), lower(tg_op), tg_table_name,
          coalesce(new.id, old.id)::text,
          case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
          case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end);
  return coalesce(new, old);
end $$;

create trigger audit_charges  after insert or update or delete on public.charges
  for each row execute function public.audit_row();
create trigger audit_payments after insert or update or delete on public.payments
  for each row execute function public.audit_row();
create trigger audit_profiles after update on public.profiles
  for each row execute function public.audit_row();
create trigger audit_periods  after update on public.billing_periods
  for each row execute function public.audit_row();

-- RLS and object privileges ship with the tables, not in a later policy PR.
-- SECURITY INVOKER views preserve the caller's future base-table policies.
-- Supabase's default table/sequence grants and default PUBLIC function EXECUTE
-- must be revoked explicitly. A privileged database owner can still maintain
-- the database; these grants are not intended to sandbox its administrator.
alter table public.fee_schedules enable row level security;
alter table public.billing_periods enable row level security;
alter table public.charges enable row level security;
alter table public.payments enable row level security;
alter table public.period_player_summaries enable row level security;
alter table public.period_account_summaries enable row level security;
alter table public.audit_log enable row level security;

revoke all on table public.fee_schedules, public.billing_periods, public.charges,
  public.payments, public.period_player_summaries, public.period_account_summaries,
  public.audit_log from public, anon, authenticated;
revoke all on table public.v_account_balance, public.v_account_ledger,
  public.v_public_roster from public, anon, authenticated;
revoke all on sequence public.audit_log_id_seq from public, anon, authenticated;

revoke all on function public.lock_billing() from public, anon, authenticated;
revoke all on function public.lock_billing_statement() from public, anon, authenticated;
revoke all on function public.require_open_billing_date(date, uuid) from public, anon, authenticated;
revoke all on function public.charges_are_immutable() from public, anon, authenticated;
revoke all on function public.payments_are_immutable() from public, anon, authenticated;
revoke all on function public.guard_billing_period() from public, anon, authenticated;
revoke all on function public.freeze_billing_history() from public, anon, authenticated;
revoke all on function public.guard_billed_game() from public, anon, authenticated;
revoke all on function public.guard_billed_registration() from public, anon, authenticated;
revoke all on function public.resolve_game_fee(uuid) from public, anon, authenticated;
revoke all on function public.resolve_no_show_fee(uuid) from public, anon, authenticated;
revoke all on function public.write_game_attendance_charges(uuid) from public, anon, authenticated;
revoke all on function public.finalise_game_attendance(uuid) from public, anon, authenticated;
revoke all on function public.assign_to_periods() from public, anon, authenticated;
revoke all on function public.write_billing_period_summaries(uuid) from public, anon, authenticated;
revoke all on function public.close_billing_period(uuid) from public, anon, authenticated;
revoke all on function public.audit_row() from public, anon, authenticated;

COMMIT;
