-- =====================================================================
-- CalBlue — migration 0003_rls.sql
-- row-level security policies and role helpers
--
-- GENERATED from docs/design/schema.sql by scripts/build_migrations.py.
-- Do not edit this file directly: edit schema.sql and regenerate, or
-- scripts/check_sql.py --check will fail on the drift.
-- =====================================================================

-- =====================================================================
-- 7. ROW-LEVEL SECURITY
--   Roles come from the JWT (synced from profiles.roles above) so that
--   policies never re-query profiles — that would recurse.
-- =====================================================================

create or replace function public.app_roles() returns text[]
language sql stable as $$
  select case
    when auth.jwt() -> 'app_metadata' ? 'roles'
      then array(select jsonb_array_elements_text(
                          auth.jwt() -> 'app_metadata' -> 'roles'))
    else array[]::text[]
  end
$$;

create or replace function public.has_role(r text) returns boolean
language sql stable as $$ select r = any(public.app_roles()) $$;

create or replace function public.is_admin() returns boolean
language sql stable as $$ select public.has_role('admin') $$;

-- Holding a scoped role over one competition, game or team. This is what
-- makes somebody the point of contact for a single tournament without
-- giving them any authority over the rest of the club.
create or replace function public.has_grant_on_competition(c uuid, roles text[])
returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.role_grants g
                  where g.account_id = auth.uid()
                    and g.competition_id = c
                    and g.role = any(roles))
$$;

create or replace function public.owns_player(p uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.players pl
                  where pl.id = p
                    and (pl.account_id = auth.uid()
                         or pl.guardian_account_id = auth.uid()))
$$;

create or replace function public.manages_game(g uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.role_grants rg
     where rg.account_id = auth.uid()
       and rg.role in ('organiser','manager','captain','coach')
       and (rg.game_id = g
            or rg.competition_id = (select competition_id
                                      from public.games where id = g)
            or rg.team_id = (select team_id from public.games where id = g)))
$$;

alter table public.profiles                  enable row level security;
alter table public.players                   enable row level security;
alter table public.role_grants               enable row level security;
alter table public.clubs                     enable row level security;
alter table public.venues                    enable row level security;
alter table public.teams                     enable row level security;
alter table public.competitions              enable row level security;
alter table public.games                     enable row level security;
alter table public.competition_registrations enable row level security;
alter table public.game_registrations        enable row level security;
alter table public.fee_schedules             enable row level security;
alter table public.billing_periods           enable row level security;
alter table public.charges                   enable row level security;
alter table public.payments                  enable row level security;
alter table public.period_player_summaries   enable row level security;
alter table public.period_account_summaries  enable row level security;
alter table public.audit_log                 enable row level security;

-- profiles: yourself, or an admin
create policy profiles_self_read on public.profiles for select
  using (id = auth.uid() or public.is_admin());
create policy profiles_self_write on public.profiles for update
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());
-- a user may not promote themselves; only an admin may change `role`
create or replace function public.guard_role_change() returns trigger
language plpgsql as $$
begin
  if new.roles is distinct from old.roles and not public.is_admin() then
    raise exception 'only an admin may change roles';
  end if;
  return new;
end $$;
create trigger profiles_guard_role before update on public.profiles
  for each row execute function public.guard_role_change();

-- players: your own identities, plus the opt-in public roster
create policy players_read on public.players for select
  using (public.is_admin()
         or account_id = auth.uid()
         or guardian_account_id = auth.uid()
         or (is_public and verification_status = 'verified'));
create policy players_insert on public.players for insert
  with check (public.is_admin() or account_id = auth.uid());
create policy players_update on public.players for update
  using (public.is_admin() or account_id = auth.uid()
         or guardian_account_id = auth.uid());
-- verification_status is admin-only, enforced by trigger rather than policy
create or replace function public.guard_verification() returns trigger
language plpgsql as $$
begin
  if new.verification_status is distinct from old.verification_status
     and not public.is_admin() then
    raise exception 'only an admin may verify a player';
  end if;
  return new;
end $$;
create trigger players_guard_verification before update on public.players
  for each row execute function public.guard_verification();

-- schedule: published events are world-readable; drafts are staff-only
create policy games_read on public.games for select
  using (status <> 'draft' or public.is_admin() or public.manages_game(id));
create policy games_write on public.games for all
  using (public.is_admin() or public.manages_game(id))
  with check (public.is_admin() or public.manages_game(id));

create policy competitions_read on public.competitions for select
  using (status <> 'draft' or public.is_admin());
create policy competitions_write on public.competitions for all
  using (public.is_admin()) with check (public.is_admin());

create policy clubs_read on public.clubs for select using (true);
create policy clubs_write on public.clubs for all
  using (public.is_admin()) with check (public.is_admin());

create policy venues_read on public.venues for select using (true);
create policy venues_write on public.venues for all
  using (public.is_admin()) with check (public.is_admin());

create policy fees_read on public.fee_schedules for select using (true);
create policy fees_write on public.fee_schedules for all
  using (public.is_admin()) with check (public.is_admin());

-- registrations: your own, plus everything on a game you run
create policy greg_read on public.game_registrations for select
  using (public.is_admin() or public.owns_player(player_id)
         or public.manages_game(game_id));
create policy greg_insert on public.game_registrations for insert
  with check (public.is_admin() or public.manages_game(game_id)
              or public.owns_player(player_id));
create policy greg_update on public.game_registrations for update
  using (public.is_admin() or public.manages_game(game_id)
         or public.owns_player(player_id));
-- a player may change their own number/position/status, never their attendance
create or replace function public.guard_attendance() returns trigger
language plpgsql as $$
begin
  if (new.attendance, new.checked_in_at, new.checked_in_by)
     is distinct from (old.attendance, old.checked_in_at, old.checked_in_by)
     and not (public.is_admin() or public.manages_game(new.game_id)) then
    raise exception 'only a captain or an admin may record attendance';
  end if;
  return new;
end $$;
create trigger greg_guard_attendance before update on public.game_registrations
  for each row execute function public.guard_attendance();

create policy creg_read on public.competition_registrations for select
  using (public.is_admin() or public.owns_player(player_id));
create policy creg_insert on public.competition_registrations for insert
  with check (public.is_admin() or public.owns_player(player_id));
create policy creg_update on public.competition_registrations for update
  using (public.is_admin() or public.owns_player(player_id));

-- money: read your own, write nothing
create policy charges_read on public.charges for select
  using (public.is_admin() or account_id = auth.uid()
         or public.owns_player(player_id));
create policy charges_write on public.charges for all
  using (public.is_admin()) with check (public.is_admin());

create policy payments_read on public.payments for select
  using (public.is_admin() or account_id = auth.uid());
create policy payments_write on public.payments for all
  using (public.is_admin()) with check (public.is_admin());

create policy periods_read on public.billing_periods for select
  using (public.is_admin());
create policy periods_write on public.billing_periods for all
  using (public.is_admin()) with check (public.is_admin());

create policy pps_read on public.period_player_summaries for select
  using (public.is_admin() or public.owns_player(player_id));
create policy pas_read on public.period_account_summaries for select
  using (public.is_admin() or account_id = auth.uid());

create policy audit_read on public.audit_log for select using (public.is_admin());

-- role_grants and teams: readable by all signed-in users, admin-writable.
-- A competition organiser may also grant captain/coach within their own
-- competition, so running a tournament does not require pestering an admin.
create policy grants_read on public.role_grants for select
  using (auth.uid() is not null);
create policy grants_write on public.role_grants for all
  using (public.is_admin()
         or (competition_id is not null
             and public.has_grant_on_competition(competition_id,
                                                 array['organiser'])))
  with check (public.is_admin()
              or (competition_id is not null and role <> 'organiser'
                  and public.has_grant_on_competition(competition_id,
                                                      array['organiser'])));
create policy teams_read on public.teams for select using (true);
create policy teams_write on public.teams for all
  using (public.is_admin()) with check (public.is_admin());
