-- =====================================================================
-- CalBlue — migration 0005_pickup_games.sql
-- team-scoped pickup game management
--
-- GENERATED from docs/design/schema.sql by scripts/build_migrations.py.
-- Do not edit this file directly: edit schema.sql and regenerate, or
-- scripts/build_migrations.py --check --target 0005_pickup_games.sql will fail on drift.
-- Apply once with migration tracking; this SQL is not replay-idempotent.
-- =====================================================================

BEGIN;

-- =====================================================================
-- 12. PICKUP GAME MANAGEMENT  (issue #33 — additive after released 0001–0004)
-- =====================================================================

-- A team organiser manages only that CalBlue team's pickups. This does NOT
-- extend manages_game(), competition authority, attendance or contact access.
-- No grants or global roles are assigned by this migration.
create function public.can_manage_pickup_team(p_team_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select auth.uid() is not null and (public.is_admin() or exists (
    select 1 from public.role_grants r
    join public.teams t on t.id = r.team_id
    join public.clubs c on c.id = t.club_id and c.is_us
    where r.account_id = auth.uid() and r.role = 'organiser' and r.team_id = p_team_id))
$$;

create policy games_pickup_staff_read on public.games for select to authenticated
  using (game_type = 'pickup' and public.can_manage_pickup_team(team_id));

-- Clients, including admins, must use the checked RPCs for pickup writes.
-- Trust actual table-owner execution, not JWT claims or a caller-set GUC.
-- Existing owner-run billing internals and explicit maintenance still work.
-- Alphabetical ordering puts this after games_touch and before billing checks.
create function public.guard_pickup_game_write() returns trigger
language plpgsql security invoker set search_path = '' as $$
begin
  if (tg_op <> 'INSERT' and old.game_type = 'pickup')
     or (tg_op <> 'DELETE' and new.game_type = 'pickup') then
    if current_user is distinct from pg_catalog.pg_get_userbyid(
        (select relowner from pg_catalog.pg_class where oid = tg_relid)) then
      raise exception 'pickup_rpc_required' using errcode = '42501';
    end if;
    if tg_op <> 'DELETE' and auth.uid() is not null then
      if tg_op = 'INSERT' then
        new.created_at := statement_timestamp();
        new.updated_at := statement_timestamp();
      else
        -- Keep a distinct CAS version even for two RPC calls in one transaction.
        new.updated_at := greatest(statement_timestamp(), old.updated_at + interval '1 microsecond');
      end if;
    end if;
  end if;
  return case when tg_op = 'DELETE' then old else new end;
end $$;
create trigger games_u_pickup_guard before insert or update or delete on public.games
  for each row execute function public.guard_pickup_game_write();

-- Private form parser. Checked save/publish callers use this after authorization
-- and the billing lock. No status, ownership, financial-lock or audit fields
-- can be smuggled through jsonb_populate_record's otherwise permissive parser.
create function public.validate_pickup_game_details(p_details jsonb) returns public.games
language plpgsql security definer set search_path = '' as $$
declare
  result public.games; key text; value text; parsed_time timestamptz;
  required_keys text[] := array['team_id','venue_id','title','field_label','timezone',
    'gather_time','start_time','end_time','capacity','registration_opens_at',
    'registration_closes_at','kit_color','notes'];
begin
  if jsonb_typeof(p_details) is distinct from 'object'
     or not (p_details ?& required_keys) then
    raise exception 'pickup_invalid' using errcode = '22023';
  end if;
  for key in select jsonb_object_keys(p_details) loop
    if not (key = any(required_keys || array['fee_override'])) then
      raise exception 'pickup_invalid' using errcode = '22023';
    end if;
    if key not in ('capacity','fee_override')
       and jsonb_typeof(p_details -> key) not in ('string','null') then
      raise exception 'pickup_invalid' using errcode = '22023';
    end if;
  end loop;
  if jsonb_typeof(p_details -> 'title') <> 'string'
     or jsonb_typeof(p_details -> 'timezone') <> 'string'
     or jsonb_typeof(p_details -> 'start_time') <> 'string' then
    raise exception 'pickup_invalid' using errcode = '22023';
  end if;
  foreach key in array array['team_id','venue_id'] loop
    value := p_details ->> key;
    if value is not null and value !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
      raise exception 'pickup_invalid' using errcode = '22023';
    end if;
  end loop;
  foreach key in array array['gather_time','start_time','end_time','registration_opens_at','registration_closes_at'] loop
    value := p_details ->> key;
    if value is not null then
      if value !~ '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]{1,6})?(Z|[+-]([01][0-9]|2[0-3]):[0-5][0-9])$' then
        raise exception 'pickup_invalid' using errcode = '22023';
      end if;
      begin
        parsed_time := value::timestamptz;
      exception when invalid_datetime_format or datetime_field_overflow or invalid_time_zone_displacement_value then
        raise exception 'pickup_invalid' using errcode = '22023';
      end;
      if not isfinite(parsed_time)
         or extract(year from parsed_time at time zone 'UTC') not between 1 and 9999 then
        raise exception 'pickup_invalid' using errcode = '22023';
      end if;
    end if;
  end loop;
  if p_details -> 'capacity' <> 'null'::jsonb then
    if jsonb_typeof(p_details -> 'capacity') <> 'number'
       or (p_details ->> 'capacity') !~ '^[0-9]{1,5}$' then
      raise exception 'pickup_invalid' using errcode = '22023';
    end if;
    if (p_details ->> 'capacity')::numeric not between 1 and 10000 then
      raise exception 'pickup_invalid' using errcode = '22023';
    end if;
  end if;
  if p_details ? 'fee_override' and p_details -> 'fee_override' <> 'null'::jsonb then
    if jsonb_typeof(p_details -> 'fee_override') <> 'number'
       or (p_details ->> 'fee_override') !~ '^[0-9]{1,8}(\.[0-9]{1,2})?$' then
      raise exception 'pickup_invalid' using errcode = '22023';
    end if;
    if (p_details ->> 'fee_override')::numeric > 99999999.99 then
      raise exception 'pickup_invalid' using errcode = '22023';
    end if;
  end if;
  select * into result from jsonb_populate_record(null::public.games, p_details);
  result.title := regexp_replace(result.title, '^[[:space:]]+|[[:space:]]+$', '', 'g');
  result.field_label := nullif(regexp_replace(result.field_label, '^[[:space:]]+|[[:space:]]+$', '', 'g'), '');
  result.kit_color := nullif(regexp_replace(result.kit_color, '^[[:space:]]+|[[:space:]]+$', '', 'g'), '');
  result.notes := nullif(regexp_replace(result.notes, '^[[:space:]]+|[[:space:]]+$', '', 'g'), '');
  if result.title = '' or char_length(result.title) > 200 or result.title ~ '[[:cntrl:]]'
     or char_length(result.field_label) > 200 or result.field_label ~ '[[:cntrl:]]'
     or char_length(result.kit_color) > 100 or result.kit_color ~ '[[:cntrl:]]'
     or char_length(result.notes) > 4000 or translate(result.notes, E'\t\n\r', '') ~ '[[:cntrl:]]'
     or char_length(result.timezone) > 100 then
    raise exception 'pickup_invalid' using errcode = '22023';
  end if;
  if result.venue_id is not null then
    select v.timezone into value from public.venues v where v.id = result.venue_id for share;
    if not found then raise exception 'pickup_invalid' using errcode = '22023'; end if;
    result.timezone := value;
  end if;
  if char_length(result.timezone) > 100
     or not exists (select 1 from pg_catalog.pg_timezone_names z where z.name = result.timezone) then
    raise exception 'pickup_invalid' using errcode = '22023';
  end if;
  result.game_date := (result.start_time at time zone result.timezone)::date;
  if extract(year from result.game_date) not between 1 and 9999
     or result.gather_time > result.start_time or result.end_time <= result.start_time
     or result.registration_opens_at > result.start_time
     or result.registration_closes_at > result.start_time
     or result.registration_opens_at > result.registration_closes_at then
    raise exception 'pickup_invalid' using errcode = '22023';
  end if;
  return result;
end $$;

create function public.pickup_game_options() returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare teams_json jsonb; venues_json jsonb;
begin
  if auth.uid() is null or not (public.is_admin() or exists (
      select 1 from public.teams t where public.can_manage_pickup_team(t.id)))
     or not exists (select 1 from public.profiles p where p.id = auth.uid()) then
    raise exception 'pickup_forbidden' using errcode = '42501';
  end if;
  select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'name',t.name) order by t.name,t.id), '[]'::jsonb)
    into teams_json from public.teams t join public.clubs c on c.id = t.club_id and c.is_us
    where public.can_manage_pickup_team(t.id);
  select coalesce(jsonb_agg(jsonb_build_object('id',v.id,'name',v.name,'timezone',v.timezone,
    'address',v.address,'map_url',v.map_url) order by v.name,v.id), '[]'::jsonb)
    into venues_json from public.venues v;
  if jsonb_array_length(teams_json) > 1000 or jsonb_array_length(venues_json) > 1000
     or exists (select 1 from jsonb_array_elements(teams_json || venues_json) item
       where char_length(item ->> 'name') > 1000 or char_length(item ->> 'address') > 4000
          or char_length(item ->> 'map_url') > 4000 or char_length(item ->> 'timezone') > 100) then
    raise exception 'pickup_options_invalid' using errcode = '22023';
  end if;
  return jsonb_build_object('can_override_fee',public.is_admin(),'teams',teams_json,'venues',venues_json);
end $$;

-- Operational notes on a published game are already readable by signed-in
-- members under 0003. This management projection does not make notes private.
create function public.list_pickup_games(p_offset integer default 0)
returns table(id uuid, team_id uuid, venue_id uuid, title text, field_label text, timezone text,
  gather_time timestamptz, start_time timestamptz, end_time timestamptz, game_date date,
  capacity integer, registration_opens_at timestamptz, registration_closes_at timestamptz,
  kit_color text, notes text, fee_override numeric, status text, cancellation_reason text,
  updated_at timestamptz, created_at timestamptz)
language plpgsql stable security definer set search_path = '' as $$
begin
  if auth.uid() is null or not (public.is_admin() or exists (
      select 1 from public.teams t where public.can_manage_pickup_team(t.id)))
     or not exists (select 1 from public.profiles p where p.id = auth.uid()) then
    raise exception 'pickup_forbidden' using errcode = '42501';
  end if;
  if p_offset is null or p_offset < 0 then
    raise exception 'pickup_invalid' using errcode = '22023';
  end if;
  return query select g.id,g.team_id,g.venue_id,g.title,g.field_label,g.timezone,g.gather_time,
    g.start_time,g.end_time,g.game_date,g.capacity,g.registration_opens_at,g.registration_closes_at,
    g.kit_color,g.notes,g.fee_override,g.status,g.cancellation_reason,g.updated_at,g.created_at
    from public.games g where g.game_type = 'pickup' and public.can_manage_pickup_team(g.team_id)
    order by g.created_at desc,g.id desc limit 21 offset p_offset;
end $$;

create function public.save_pickup_game(p_game_id uuid, p_expected_updated_at timestamptz, p_details jsonb)
returns table(id uuid, team_id uuid, venue_id uuid, title text, field_label text, timezone text,
  gather_time timestamptz, start_time timestamptz, end_time timestamptz, game_date date,
  capacity integer, registration_opens_at timestamptz, registration_closes_at timestamptz,
  kit_color text, notes text, fee_override numeric, status text, cancellation_reason text,
  updated_at timestamptz, created_at timestamptz)
language plpgsql security definer set search_path = '' as $$
declare previous public.games; details public.games; saved_id uuid; affected integer;
begin
  if auth.uid() is null or not (public.is_admin() or exists (
      select 1 from public.teams t where public.can_manage_pickup_team(t.id))) then
    raise exception 'pickup_forbidden' using errcode = '42501';
  end if;
  if (p_game_id is null) <> (p_expected_updated_at is null)
     or (p_expected_updated_at is not null and (not isfinite(p_expected_updated_at)
       or extract(year from p_expected_updated_at at time zone 'UTC') not between 1 and 9999)) then
    raise exception 'pickup_invalid' using errcode = '22023';
  end if;
  if public.is_admin() is not true and p_details ? 'fee_override' then
    raise exception 'pickup_fee_forbidden' using errcode = '42501';
  end if;
  perform public.lock_billing();
  if not exists (select 1 from public.profiles p where p.id = auth.uid()) then
    raise exception 'pickup_forbidden' using errcode = '42501';
  end if;
  if p_game_id is not null then
    select g.* into previous from public.games g where g.id = p_game_id for update;
    if not found or previous.game_type <> 'pickup' then
      raise exception 'pickup_conflict' using errcode = 'P0001';
    end if;
    if public.can_manage_pickup_team(previous.team_id) is not true then
      raise exception 'pickup_forbidden' using errcode = '42501';
    end if;
    if previous.updated_at is distinct from p_expected_updated_at
       or previous.status not in ('draft','published','reg_closed')
       or previous.attendance_locked_at is not null
       or exists (select 1 from public.charges c where c.game_id = p_game_id) then
      raise exception 'pickup_conflict' using errcode = 'P0001';
    end if;
  end if;
  details := public.validate_pickup_game_details(p_details);
  if public.can_manage_pickup_team(details.team_id) is not true then
    raise exception 'pickup_forbidden' using errcode = '42501';
  end if;
  if details.team_id is not null then
    perform 1 from public.teams t join public.clubs c on c.id = t.club_id
      where t.id = details.team_id and c.is_us for share of t,c;
    if not found then raise exception 'pickup_invalid' using errcode = '22023'; end if;
  end if;
  if p_game_id is null then
    insert into public.games as g(team_id,venue_id,game_type,title,field_label,timezone,gather_time,
      start_time,end_time,capacity,registration_opens_at,registration_closes_at,kit_color,notes,
      fee_override,status,created_by)
    values(details.team_id,details.venue_id,'pickup',details.title,details.field_label,details.timezone,
      details.gather_time,details.start_time,details.end_time,details.capacity,details.registration_opens_at,
      details.registration_closes_at,details.kit_color,details.notes,details.fee_override,'draft',auth.uid())
    returning g.id into saved_id;
  else
    if details.capacity is not null and details.capacity < (select count(*) from public.game_registrations r
        where r.game_id = p_game_id and r.status = 'registered' and r.participation in ('player','keeper')) then
      raise exception 'pickup_capacity_conflict' using errcode = '22023';
    end if;
    update public.games g set team_id=details.team_id,venue_id=details.venue_id,title=details.title,
      field_label=details.field_label,timezone=details.timezone,gather_time=details.gather_time,
      start_time=details.start_time,end_time=details.end_time,capacity=details.capacity,
      registration_opens_at=details.registration_opens_at,registration_closes_at=details.registration_closes_at,
      kit_color=details.kit_color,notes=details.notes,
      fee_override=case when p_details ? 'fee_override' then details.fee_override else g.fee_override end
    where g.id = p_game_id and g.updated_at = p_expected_updated_at
    returning g.id into saved_id;
  end if;
  get diagnostics affected = row_count;
  if affected <> 1 or saved_id is null then raise exception 'pickup_conflict' using errcode = 'P0001'; end if;
  return query select g.id,g.team_id,g.venue_id,g.title,g.field_label,g.timezone,g.gather_time,
    g.start_time,g.end_time,g.game_date,g.capacity,g.registration_opens_at,g.registration_closes_at,
    g.kit_color,g.notes,g.fee_override,g.status,g.cancellation_reason,g.updated_at,g.created_at
    from public.games g where g.id = saved_id;
end $$;

create function public.transition_pickup_game(p_game_id uuid, p_expected_updated_at timestamptz,
  p_action text, p_reason text default null)
returns table(id uuid, team_id uuid, venue_id uuid, title text, field_label text, timezone text,
  gather_time timestamptz, start_time timestamptz, end_time timestamptz, game_date date,
  capacity integer, registration_opens_at timestamptz, registration_closes_at timestamptz,
  kit_color text, notes text, fee_override numeric, status text, cancellation_reason text,
  updated_at timestamptz, created_at timestamptz)
language plpgsql security definer set search_path = '' as $$
declare previous public.games; validated public.games; next_status text; reason text; affected integer;
begin
  if auth.uid() is null or not (public.is_admin() or exists (
      select 1 from public.teams t where public.can_manage_pickup_team(t.id))) then
    raise exception 'pickup_forbidden' using errcode = '42501';
  end if;
  reason := nullif(regexp_replace(p_reason, '^[[:space:]]+|[[:space:]]+$', '', 'g'), '');
  if p_game_id is null or p_expected_updated_at is null or not isfinite(p_expected_updated_at)
     or extract(year from p_expected_updated_at at time zone 'UTC') not between 1 and 9999
     or p_action is null or p_action not in ('publish','close','cancel')
     or char_length(reason) > 2000 or translate(reason, E'\t\n\r', '') ~ '[[:cntrl:]]'
     or (p_action = 'cancel' and reason is null) or (p_action <> 'cancel' and reason is not null) then
    raise exception 'pickup_invalid' using errcode = '22023';
  end if;
  perform public.lock_billing();
  if not exists (select 1 from public.profiles p where p.id = auth.uid()) then
    raise exception 'pickup_forbidden' using errcode = '42501';
  end if;
  select g.* into previous from public.games g where g.id = p_game_id for update;
  if not found or previous.game_type <> 'pickup' then
    raise exception 'pickup_conflict' using errcode = 'P0001';
  end if;
  if public.can_manage_pickup_team(previous.team_id) is not true then
    raise exception 'pickup_forbidden' using errcode = '42501';
  end if;
  if previous.updated_at is distinct from p_expected_updated_at
     or previous.attendance_locked_at is not null
     or exists (select 1 from public.charges c where c.game_id = p_game_id)
     or not ((p_action = 'publish' and previous.status = 'draft' and previous.start_time > statement_timestamp())
       or (p_action = 'close' and previous.status = 'published')
       or (p_action = 'cancel' and previous.status in ('draft','published','reg_closed'))) then
    raise exception 'pickup_conflict' using errcode = 'P0001';
  end if;
  if p_action = 'publish' then
    -- Legacy/owner-maintained drafts must satisfy the same form contract.
    -- Require an explicit edit/save if normalization or venue changes are
    -- needed; publishing must not silently rewrite operational details.
    validated := public.validate_pickup_game_details(jsonb_build_object(
      'team_id',previous.team_id,'venue_id',previous.venue_id,'title',previous.title,
      'field_label',previous.field_label,'timezone',previous.timezone,
      'gather_time',previous.gather_time,'start_time',previous.start_time,'end_time',previous.end_time,
      'capacity',previous.capacity,'registration_opens_at',previous.registration_opens_at,
      'registration_closes_at',previous.registration_closes_at,'kit_color',previous.kit_color,
      'notes',previous.notes,'fee_override',previous.fee_override));
    if (validated.title,validated.field_label,validated.kit_color,validated.notes,validated.timezone,validated.game_date)
       is distinct from (previous.title,previous.field_label,previous.kit_color,previous.notes,previous.timezone,previous.game_date)
       or (previous.team_id is not null and not exists (
         select 1 from public.teams t join public.clubs c on c.id=t.club_id
         where t.id=previous.team_id and c.is_us)) then
      raise exception 'pickup_invalid' using errcode = '22023';
    end if;
  end if;
  next_status := case p_action when 'publish' then 'published' when 'close' then 'reg_closed' else 'cancelled' end;
  return query update public.games g set status=next_status,
    cancellation_reason=case when p_action = 'cancel' then reason else g.cancellation_reason end
    where g.id = p_game_id and g.updated_at = p_expected_updated_at
    returning g.id,g.team_id,g.venue_id,g.title,g.field_label,g.timezone,g.gather_time,
      g.start_time,g.end_time,g.game_date,g.capacity,g.registration_opens_at,g.registration_closes_at,
      g.kit_color,g.notes,g.fee_override,g.status,g.cancellation_reason,g.updated_at,g.created_at;
  get diagnostics affected = row_count;
  if affected <> 1 then raise exception 'pickup_conflict' using errcode = 'P0001'; end if;
end $$;

revoke all on function public.can_manage_pickup_team(uuid) from public, anon, authenticated;
revoke all on function public.guard_pickup_game_write() from public, anon, authenticated;
revoke all on function public.validate_pickup_game_details(jsonb) from public, anon, authenticated;
revoke all on function public.pickup_game_options() from public, anon, authenticated;
revoke all on function public.list_pickup_games(integer) from public, anon, authenticated;
revoke all on function public.save_pickup_game(uuid, timestamptz, jsonb) from public, anon, authenticated;
revoke all on function public.transition_pickup_game(uuid, timestamptz, text, text) from public, anon, authenticated;
grant execute on function public.can_manage_pickup_team(uuid), public.pickup_game_options(),
  public.list_pickup_games(integer), public.save_pickup_game(uuid, timestamptz, jsonb),
  public.transition_pickup_game(uuid, timestamptz, text, text) to authenticated;

COMMIT;
